export interface HistoricalKingdomRegion {
  id: string;
  dynastyKey: "chola" | "pandya" | "chera" | "pallava";
  nameEn: string;
  nameTa: string;
  symbolName: string;
  color: string;
  fillColor: string;
  fillOpacity: number;
  capitalEn: string;
  capitalTa: string;
  reignYears: string;
  polygon: [number, number][]; // Multi-vertex detailed organic boundary
  famousRulers: string[];
  historicalOverview: string;
  famousBattles: string[];
  architecturalMonuments: string[];
  literatureWorks: string[];
  keyTradePorts: string[];
  imageUrl?: string;
}

export interface HistoricalEra {
  id: string;
  titleEn: string;
  titleTa: string;
  timePeriod: string;
  description: string;
  kingdoms: HistoricalKingdomRegion[];
}

export const HISTORICAL_ERAS: HistoricalEra[] = [
  {
    id: "sangam",
    titleEn: "Sangam Era & Early Kingdoms",
    titleTa: "சங்க கால மூவேந்தர் சாம்ராஜ்யம்",
    timePeriod: "~300 BCE – 300 CE",
    description: "The classical golden age of early Tamilakam ruled by the Muvendar (Three Crowned Kings: Chola, Chera, Pandya) with flourishing sea trade with Rome, Greece, and Southeast Asia, recorded in Sangam literature.",
    kingdoms: [
      {
        id: "sangam_chola",
        dynastyKey: "chola",
        nameEn: "Early Chola Kingdom (Uraiyur)",
        nameTa: "சங்க காலச் சோழ நாடு",
        symbolName: "Tiger Flag (புலிகொடி)",
        color: "#f59e0b",
        fillColor: "#f59e0b",
        fillOpacity: 0.35,
        capitalEn: "Uraiyur & Kaveripoompattinam (Poompuhar)",
        capitalTa: "உறையூர் & காவிரிப்பூம்பட்டினம்",
        reignYears: "300 BCE – 300 CE",
        polygon: [
          [12.10, 79.55],
          [11.95, 79.80],
          [11.75, 79.85],
          [11.35, 79.80],
          [11.00, 79.88],
          [10.45, 79.85],
          [10.35, 79.20],
          [10.45, 78.80],
          [10.75, 78.35],
          [11.15, 78.70],
          [11.50, 78.75],
          [11.80, 79.15],
          [12.10, 79.55],
        ],
        famousRulers: ["Karikala Chola (கரிகாலச் சோழன்)", "Nalankilli", "Killivalavan"],
        historicalOverview: "Karikala Chola defeated the combined armies of Cheras and Pandyas at the legendary Battle of Venni. He constructed the world's oldest functional water-diversion dam, Kallanai (Grand Anicut), across the Cauvery River and established Poompuhar as a world maritime port.",
        famousBattles: ["Battle of Venni (வெண்ணிப் போர்)", "Battle of Vagaipparandalal"],
        architecturalMonuments: ["Kallanai (Grand Anicut Dam)", "Poompuhar Sangam Port Structures"],
        literatureWorks: ["Pattinappalai (பட்டினப்பாலை)", "Purananuru (புறநானூறு)", "Silappatikaram"],
        keyTradePorts: ["Kaveripoompattinam (Poompuhar)", "Arikamedu (Poduke)"],
        imageUrl: "/assets/map/chola_history.jpg",
      },
      {
        id: "sangam_pandya",
        dynastyKey: "pandya",
        nameEn: "Early Pandya Kingdom (Madurai & Korkai)",
        nameTa: "சங்க காலப் பாண்டிய நாடு",
        symbolName: "Twin Fish Flag (இரட்டை கயல் கொடி)",
        color: "#ef4444",
        fillColor: "#ef4444",
        fillOpacity: 0.35,
        capitalEn: "Madurai & Korkai (Pearl Port)",
        capitalTa: "மதுரை & கொற்கை",
        reignYears: "300 BCE – 300 CE",
        polygon: [
          [10.45, 78.45],
          [10.35, 79.20],
          [9.95, 78.85],
          [9.60, 78.90],
          [9.45, 79.35],
          [9.10, 78.75],
          [8.50, 78.25],
          [8.08, 77.55],
          [8.35, 77.55],
          [8.75, 77.25],
          [9.45, 77.40],
          [9.85, 77.65],
          [10.05, 77.65],
          [10.15, 78.10],
          [10.45, 78.45],
        ],
        famousRulers: ["Nedunjeliyan II (Talaiyalanganathu Seruvendra Pandyan)", "Mudukudumi Paruvaluthi"],
        historicalOverview: "The Pandyas were legendary patrons of the Tamil Sangam Academies in Madurai where Tamil grammar, poetry, and philosophy flourished. Korkai port was renowned globally for natural sea pearl harvesting mentioned by Pliny and Ptolemy.",
        famousBattles: ["Battle of Talaiyalanganam (தலைஆலங்கானத்துப் போர்)"],
        architecturalMonuments: ["Mangulam Tamil-Brahmi Jain Caves", "Korkai Sangam Pearl Docks"],
        literatureWorks: ["Maduraikkanchi (மதுரைக்காஞ்சி)", "Nedunalvadai (நெடுநல்வாடை)", "Tirukkural"],
        keyTradePorts: ["Korkai (கொற்கை)", "Alagankulam (அழகன்குளம்)"],
        imageUrl: "/assets/map/pandya_history.jpg",
      },
      {
        id: "sangam_chera",
        dynastyKey: "chera",
        nameEn: "Early Chera Kingdom (Vanchi / Karur)",
        nameTa: "சங்க காலச் சேர நாடு",
        symbolName: "Bow and Arrow Flag (வில் கொடி)",
        color: "#10b981",
        fillColor: "#10b981",
        fillOpacity: 0.35,
        capitalEn: "Vanji (Karur) & Muziris (Kodungallur)",
        capitalTa: "வஞ்சி (கரூர்) & முசிறி",
        reignYears: "300 BCE – 300 CE",
        polygon: [
          [12.35, 77.75],
          [12.20, 78.05],
          [11.85, 78.15],
          [11.60, 78.50],
          [11.15, 77.95],
          [10.75, 78.35],
          [10.55, 77.60],
          [9.85, 77.65],
          [9.80, 77.10],
          [10.45, 76.95],
          [10.80, 76.65],
          [11.25, 76.35],
          [11.65, 76.50],
          [12.35, 77.75],
        ],
        famousRulers: ["Cheran Senguttuvan (சேரன் செங்குட்டுவன்)", "Imayavaramban Neduncheralathan"],
        historicalOverview: "Cheran Senguttuvan marched to the Himalayas to bring stone for the temple of Kannagi, heroine of Silappatikaram. Chera port Muziris handled immense Roman pepper trade, where Roman gold coins ('denarii') flooded into Kongu Nadu.",
        famousBattles: ["Northern Himalayan Expedition of Senguttuvan", "Naval Victory over Pirates at Sea"],
        architecturalMonuments: ["Pugaliyur Karur Rock Inscriptions", "Kannagi Kovil (Mangaladevi)"],
        literatureWorks: ["Padirruppattu (பதிற்றுப்பத்து)", "Silappatikaram (இலங்கோவடிகள்)"],
        keyTradePorts: ["Muziris (முசிறி)", "Tondi (தொண்டி)", "Karuvoor"],
        imageUrl: "/assets/map/chera_history.jpg",
      },
    ],
  },
  {
    id: "pallava",
    titleEn: "Pallava & Bhakti Era",
    titleTa: "பல்லவர் பொற்காலம் & பக்தி இயக்கம்",
    timePeriod: "~600 CE – 850 CE",
    description: "The era of granitic rock-cut cave temples, monolithic Rathas, and coastal art of Mamallapuram, alongside the devotional Nayanmars and Alvars Bhakti movement.",
    kingdoms: [
      {
        id: "pallava_tondai",
        dynastyKey: "pallava",
        nameEn: "Pallava Kingdom (Tondaimandalam)",
        nameTa: "பல்லவத் தொண்டை மண்டலம்",
        symbolName: "Nandi Bull Flag (நந்தி கொடி)",
        color: "#8b5cf6",
        fillColor: "#8b5cf6",
        fillOpacity: 0.35,
        capitalEn: "Kanchipuram & Mamallapuram Port",
        capitalTa: "காஞ்சிபுரம் & மாமல்லபுரம்",
        reignYears: "550 CE – 890 CE",
        polygon: [
          [13.55, 79.85],
          [13.50, 80.15],
          [13.23, 80.32],
          [12.90, 80.26],
          [12.45, 80.12],
          [11.85, 79.85],
          [11.80, 79.15],
          [12.10, 78.75],
          [12.45, 78.85],
          [12.75, 78.85],
          [13.25, 79.55],
          [13.55, 79.85],
        ],
        famousRulers: ["Mahendravarman I (மகேந்திரவர்மன்)", "Narasimhavarman I (Mamalla - மாமல்லன்)", "Nandivarman II"],
        historicalOverview: "Narasimhavarman I defeated Pulakeshin II of Chalukya Empire and captured Vatapi. Pallava kings pioneered South Indian temple architecture with structural stone masterpieces in Mamallapuram and Kanchipuram.",
        famousBattles: ["Battle of Manimangalam", "Conquest of Vatapi (வாதாபிப் போர்)"],
        architecturalMonuments: ["Mamallapuram Shore Temple", "Pancha Rathas & Descent of the Ganges", "Kanchi Kailasanathar Temple"],
        literatureWorks: ["Mattavilasa Prahasana", "Tevaram Hymns", "Divya Prabandham"],
        keyTradePorts: ["Mamallapuram (மாமல்லபுரம்)", "Mylapore"],
        imageUrl: "/assets/map/pallava_history.jpg",
      },
    ],
  },
  {
    id: "imperial_chola",
    titleEn: "Imperial Chola Golden Empire",
    titleTa: "பிற்காலச் சோழப் பேரரசு (இராசராசன் & இராசேந்திரன்)",
    timePeriod: "~985 CE – 1150 CE",
    description: "The height of Tamil military and naval grandeur. Rajaraja Chola I and Rajendra Chola I built a maritime super-empire spanning South India, Sri Lanka, Maldives, Malaya, and Sumatra.",
    kingdoms: [
      {
        id: "imperial_chola_realm",
        dynastyKey: "chola",
        nameEn: "Imperial Chola Heartland & Dominions",
        nameTa: "சோழப் பேரரசு",
        symbolName: "Golden Royal Tiger Emblem (பொன் புலி சின்னம்)",
        color: "#f59e0b",
        fillColor: "#f59e0b",
        fillOpacity: 0.45,
        capitalEn: "Thanjavur & Gangaikonda Cholapuram",
        capitalTa: "தஞ்சாவூர் & கங்கை கொண்ட சோழபுரம்",
        reignYears: "985 CE – 1279 CE",
        polygon: [
          [13.55, 79.85],
          [13.23, 80.32],
          [12.45, 80.12],
          [11.85, 79.85],
          [11.00, 79.88],
          [10.45, 79.85],
          [9.45, 79.35],
          [8.08, 77.55],
          [8.75, 77.25],
          [9.80, 77.10],
          [10.80, 76.65],
          [11.65, 76.50],
          [12.90, 78.20],
          [13.55, 79.85],
        ],
        famousRulers: ["Rajaraja Chola I (இராசராச சோழன்)", "Rajendra Chola I (இராசேந்திர சோழன்)", "Kulottunga Chola I"],
        historicalOverview: "Rajaraja Chola I commissioned the grand Brihadisvara Temple of Thanjavur, established a standardized land revenue survey system, and conquered Sri Lanka. His son Rajendra Chola I marched to the Ganges River and launched a massive trans-oceanic naval invasion against Srivijaya Empire in Malaysia/Indonesia.",
        famousBattles: ["Battle of Kandalur Salai (காந்தளூர் சாலை)", "Gangetic Expedition", "Srivijaya Naval Expedition (கடாரம் கொண்டான்)"],
        architecturalMonuments: ["Thanjavur Brihadisvara Temple (Big Temple)", "Gangaikonda Cholapuram UNESCO Temple", "Darasuram Airavatesvara Temple"],
        literatureWorks: ["Kalingattu Parani (கலிங்கத்துப்பரணி)", "Periya Puranam", "Kamba Ramayanam"],
        keyTradePorts: ["Nagapattinam (நாகப்பட்டினம்)", "Kadaram (Kedah, Malaysia)", "Sri Lanka Ports"],
        imageUrl: "/assets/map/chola_empire.jpg",
      },
    ],
  },
  {
    id: "later_pandya",
    titleEn: "Later Pandya Empire Zenith",
    titleTa: "பிற்காலப் பாண்டியப் பேரரசு (சுந்தர பாண்டியன்)",
    timePeriod: "~1216 CE – 1311 CE",
    description: "The dramatic resurrection of Pandya supremacy under Jatavarman Sundara Pandyan I, who conquered all of South India and Ceylon, making Madurai the wealthiest metropolis in Asia.",
    kingdoms: [
      {
        id: "later_pandya_realm",
        dynastyKey: "pandya",
        nameEn: "Later Pandya Empire",
        nameTa: "பிற்காலப் பாண்டிய சாம்ராஜ்யம்",
        symbolName: "Imperial Twin Fish Banner (பாண்டிய கயல் கொடி)",
        color: "#ef4444",
        fillColor: "#ef4444",
        fillOpacity: 0.45,
        capitalEn: "Madurai & Tenkasi",
        capitalTa: "மதுரை & தென்காசி",
        reignYears: "1216 CE – 1311 CE",
        polygon: [
          [13.25, 79.55],
          [12.90, 80.26],
          [11.85, 79.85],
          [10.45, 79.85],
          [9.45, 79.35],
          [8.08, 77.55],
          [8.75, 77.25],
          [9.80, 77.10],
          [10.80, 76.65],
          [11.95, 77.80],
          [12.65, 79.05],
          [13.25, 79.55],
        ],
        famousRulers: ["Jatavarman Sundara Pandyan I (சடாவர்மன் சுந்தரபாண்டியன்)", "Maravarman Kulasekara Pandyan I"],
        historicalOverview: "Jatavarman Sundara Pandyan I defeated the Cholas, Hoysalas, and Kakatiyas, gilding the towers of Srirangam and Chidambaram with pure gold. Venetian traveler Marco Polo visited Pandya ports in 1292 CE and wrote: 'It is the finest and most noble province in the world.'",
        famousBattles: ["Battle of Samayapuram", "Conquest of Ceylon & Hoysala Realm"],
        architecturalMonuments: ["Tenkasi Kasi Viswanathar Temple", "Srirangam Gold Gopuram Additions", "Madurai Meenakshi Eastern Gopuram"],
        literatureWorks: ["Marco Polo's Travels Chronicles", "Pandya Prasasti Inscriptions"],
        keyTradePorts: ["Kayalpatnam (காயல்பட்டினம்)", "Korkai", "Devipattinam"],
        imageUrl: "/assets/map/pandya_empire.jpg",
      },
    ],
  },
];
