"""
Seed dataset for Feature 5 — Tamil History Timeline & Knowledge Explorer.
Provides structured, source-attributed historical milestone entries spanning ancient to modern eras.
"""

SEED_HISTORY_ITEMS = [
    # ---------------------------------------------------------------- Sangam Era
    {
        "slug": "keeladi-excavations",
        "content_type": "history",
        "title_ta": "கீழடி நகர நாகரிகக் கண்டுபிடிப்பு",
        "title_en": "Keeladi Vaigai Urban Civilization Discovery",
        "category": "History",
        "summary_ta": "வைகை ஆற்றுப்படுகையில் கி.மு. 6-ஆம் நூற்றாண்டைச் சேர்ந்த தொன்மையான நகர நாகரிகமும் எழுத்தறிவும் கண்டறியப்பட்டது.",
        "summary_en": "Archaeological excavations at Keeladi along the Vaigai River reveal a sophisticated, literate urban civilization dating back to 6th Century BCE.",
        "content_ta": "சிவகங்கை மாவட்டம் கீழடியில் தமிழ்நாடு அரசு தொல்லியல் துறை நடத்திய அகழ்வாராய்ச்சியில் கி.மு. 6-ஆம் நூற்றாண்டைச் சேர்ந்த வைகை நதிக்கரை நகர நாகரிகம் வெளிப்பட்டது. இங்கு கண்டெடுக்கப்பட்ட பானையோடுகளில் தமிழ்-பிராமி எழுத்துக்கள் செதுக்கப்பட்டுள்ளன. செங்கல் கட்டிடங்கள், திறந்தவெளி வடிகால் அமைப்புகள், நெசவுக்கருவிகள், சூதாட்டக் காய்கள் மற்றும் தங்க ஆபரணங்கள் மூலம் பண்டையத் தமிழர்கள் எழுத்தறிவும் நகர நாகரிக மேன்மையும் பெற்று விளங்கியது அறிவியல் பூர்வமாக (AMS Carbon Dating) நிரூபிக்கப்பட்டுள்ளது.",
        "content_en": "Extensive excavations at Keeladi near Madurai by the Tamil Nadu State Department of Archaeology produced ground-breaking evidence of an advanced urban settlement along the Vaigai River valley dating to 6th Century BCE (accelerator mass spectrometry carbon-dated by Beta Analytic, USA). Thousands of artifacts—including Tamil-Brahmi inscribed potsherds, ring wells, structural brick walls, weaving spindles, and agate beads—conclusively prove widespread literacy and urban living in Tamilakam contemporary with northern Mahajanapadas.",
        "date_order": -600,
        "date_label": "c. 6th – 3rd Century BCE",
        "era": "Sangam Era",
        "region": "Keeladi, Sivagangai",
        "period": "Early Sangam Antiquity",
        "location_name": "Keeladi Museum & Archaeological Site, Sivagangai",
        "latitude": 9.8624,
        "longitude": 78.1882,
        "image_url": "/assets/history/keeladi-excavations.jpg",
        "image_caption": "Archaeological brick structures and Tamil-Brahmi potsherds discovered at Keeladi",
        "source_type": "archaeological_report",
        "source_name": "Tamil Nadu Archaeology Department & Ezhuthaani Editorial",
        "source_url": "https://tnarch.gov.in/keeladi",
        "license": "Government Open Data",
        "tags": "history,keeladi,archaeology,vaigai,sangam,brahmi",
        "related_slugs": "sangam-assembly-foundations,ancient-maritime-trade",
    },
    {
        "slug": "sangam-assembly-foundations",
        "content_type": "history",
        "title_ta": "கடைச்சங்கக் கழகம் (மதுரை)",
        "title_en": "The Third Tamil Sangam at Madurai",
        "category": "History",
        "summary_ta": "பண்டைய மதுரையில் சங்கம் அமைத்து புலவர்கள் தமிழ் செய்யுள்களை ஆய்ந்து தொகுத்த காலகட்டம்.",
        "summary_en": "The legendary literary academy convened at Madurai under Pandyan patronage to codify classical Tamil poetry.",
        "content_ta": "பண்டைய தமிழ்நாட்டில் பாண்டிய மன்னர்களின் ஆதரவோடு மதுரையில் கடைச்சங்கம் நிறுவப்பட்டது. 473-க்கும் மேற்பட்ட புலவர்கள் (30-க்கும் மேற்பட்ட பெண்பாற் புலவர்கள் உட்பட) ஒன்றாகக் கூடி தமிழ் மொழியின் இலக்கண, இலக்கியங்களை உருவாக்கினார்கள். எட்டுத்தொகை மற்றும் பத்துப்பாட்டு நூல்கள் இச்சங்க காலத்தில் தொகுக்கப்பட்டன. இது தமிழ் நாகரிகத்தின் பொற்காலமாகும்.",
        "content_en": "The Third Tamil Sangam convened at ancient Madurai under the royal patronage of the Pandyan dynasty. Over 473 poets (including over 30 revered female poets such as Avvaiyar, Velliveethiyar, and Kakkaipadiniyar) assembled to refine grammar and compose epic poetry. This period gave birth to the foundational Ettuthogai and Pattupattu anthologies, establishing Tamil as a premier classical literary language.",
        "date_order": -300,
        "date_label": "c. 300 BCE – 300 CE",
        "era": "Sangam Era",
        "region": "Madurai, Tamilakam",
        "period": "Classical Antiquity",
        "location_name": "Ancient Madurai Sangam Complex, Tamil Nadu",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "image_url": "/assets/history/sangam-assembly.jpg",
        "image_caption": "Palm-leaf manuscript heritage of Sangam literary assemblies at Madurai",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1276701) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1276701",
        "license": "CC BY-SA 4.0",
        "tags": "history,sangam,madurai,pandya,poetry",
        "related_slugs": "thirukkural-composition,keeladi-excavations",
    },
    {
        "slug": "ancient-maritime-trade",
        "content_type": "history",
        "title_ta": "பண்டையத் தமிழர்களின் சர்வதேசக் கடல் வணிகம்",
        "title_en": "Sangam Maritime Trade with Rome & Greece",
        "category": "History",
        "summary_ta": "பூம்புகார், முசிறி, அரிகமேடு துறைமுகங்கள் வழியாக ரோமானியப் பேரரசுடன் நடைபெற்ற சர்வதேச வணிகம்.",
        "summary_en": "Extensive international maritime trade connecting ancient Tamil ports with the Roman Empire and Ancient Greece.",
        "content_ta": "சங்க காலத்தில் தமிழர்கள் சர்வதேசக் கடல் வணிகத்தில் சிறந்து விளங்கினார்கள். பூம்புகார் (காவிரிப்பூம்பட்டினம்), முசிறி, கொற்கை மற்றும் அரிகமேடு ஆகிய துறைமுகங்களிலிருந்து மிளகு, முத்து, சங்கு, பருத்தி உடைகள் மற்றும் வாசனைப் பொருட்கள் ரோமானியப் பேரரசுக்கு ஏற்றுமதி செய்யப்பட்டன. பதிலுக்கு ரோமானிய தங்க நாணயங்கள் இறக்குமதி செய்யப்பட்டன. அரிகமேட்டில் கண்டெடுக்கப்பட்ட ரோமானியப் பானைகளும் நாணயங்களும் இதற்குச் சான்றாகும்.",
        "content_en": "During the Sangam Era, Tamil kingdoms maintained sophisticated global trade networks spanning the Mediterranean and Southeast Asia. Ports such as Poompuhar, Muziris, Korkai, and Arikamedu exported black pepper ('Black Gold'), fine pearls, textiles, and ivory to the Roman Empire in exchange for Roman gold coinage and wine amphorae, as documented in Roman records by Pliny the Elder and Ptolemy.",
        "date_order": -100,
        "date_label": "c. 100 BCE – 200 CE",
        "era": "Sangam Era",
        "region": "Poompuhar & Arikamedu",
        "period": "Classical Trade Era",
        "location_name": "Poompuhar Ancient Port, Mayiladuthurai",
        "latitude": 11.1444,
        "longitude": 79.8556,
        "image_url": "/assets/history/maritime-trade.jpg",
        "image_caption": "Ancient maritime trade routes and Roman gold coins unearthed in Tamilakam",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534002) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534002",
        "license": "CC BY-SA 4.0",
        "tags": "history,maritime,trade,rome,arikamedu,poompuhar",
        "related_slugs": "keeladi-excavations,chola-rise-vijayalaya",
    },

    # ---------------------------------------------------------------- Classical Era
    {
        "slug": "thirukkural-composition",
        "content_type": "history",
        "title_ta": "திருக்குறள் இயற்றப்படுதல்",
        "title_en": "Composition of the Thirukkural",
        "category": "History",
        "summary_ta": "திருவள்ளுவரால் உலகப் பொதுமறையான 1,330 திருக்குறள்கள் இயற்றப்பட்ட காலகட்டம்.",
        "summary_en": "Philosopher Thiruvalluvar composes the Thirukkural, establishing universal ethics and governance principles.",
        "content_ta": "சங்க காலத்தின் பிற்பகுதியில் அல்லது சங்கம் மருவிய காலத்தில் திருவள்ளுவர் திருக்குறளை இயற்றினார். 133 அதிகாரங்களில் 1,330 குறட்பாக்களைக் கொண்டு அறத்துப்பால், பொருட்பால், இன்பத்துப்பால் என்ற முப்பால்களாகப் பிரிக்கப்பட்டது. எந்த ஒரு மதத்தையும் சாதியையும் சாராமல் மனித குலம் முழுமைக்குமான உலகளாவிய வாழ்வியல் நெறிகளை திருக்குறள் வழங்குகிறது.",
        "content_en": "Authored by Sage Thiruvalluvar, the Thirukkural stands as the pinnacle of Tamil ethical philosophy. Comprising 1,330 couplets across 133 chapters, it is structured into three parts: Aram (Righteousness), Porul (Wealth & Governance), and Inbam (Love). Its strictly secular, universal worldview has led to its translation into over 40 world languages.",
        "date_order": 100,
        "date_label": "c. 1st – 5th Century CE",
        "era": "Classical Era",
        "region": "Mylapore / Ancient Tamilakam",
        "period": "Post-Sangam Classical Era",
        "location_name": "Mylapore Valluvar Kottam, Chennai",
        "latitude": 13.0519,
        "longitude": 80.2435,
        "image_url": "/assets/history/thirukkural-composition.jpg",
        "image_caption": "Statue representation of Thiruvalluvar authoring the Thirukkural",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q312480) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q312480",
        "license": "CC BY-SA 4.0",
        "tags": "history,thirukkural,thiruvalluvar,ethics,post-sangam",
        "related_slugs": "silappatikaram-epic,sangam-assembly-foundations",
    },
    {
        "slug": "silappatikaram-epic",
        "content_type": "history",
        "title_ta": "சிலப்பதிகாரம் காப்பியம்",
        "title_en": "The Epic of Silappatikaram",
        "category": "History",
        "summary_ta": "இளங்கோ அடிகளால் இயற்றப்பட்ட தமிழின் முதல் ஐம்பெருங்காப்பியம் (கோவலன் - கண்ணகி வரலாறு).",
        "summary_en": "Ilango Adigal authors Tamil Nadu's first great literary epic detailing justice, Kannagi's devotion, and royal ethics.",
        "content_ta": "சேர இளவரசர் இளங்கோ அடிகளால் இயற்றப்பட்ட சிலப்பதிகாரம் தமிழின் முதல் காப்பியமாகும். பூம்புகாரின் வணிகன் கோவலன், அவன் மனைவி கண்ணகி மற்றும் மாதவி ஆகியோரின் வாழ்க்கையை அடிப்படையாகக் கொண்டது. பாண்டிய மன்னன் நெடுஞ்செழியன் தவறான தீர்ப்பளித்ததால் மதுரையை கண்ணகி எரித்த கதையும், 'அரசியல் பிழைத்தோர்க்கு அறம்கூற்றாவதும்' என்ற நீதித் தத்துவமும் இக்காப்பியத்தின் மையக்கருத்தாகும்.",
        "content_en": "Composed by Prince-turned-monk Ilango Adigal, Silappatikaram ('The Tale of the Anklet') is the first of the Five Great Epics of Tamil Literature. Set across Poompuhar, Madurai, and Vanci, it recounts the tragic story of Kovalan and Kannagi. When King Nedunjeliyan mistakenly executes Kovalan, Kannagi proves his innocence in court, burning Madurai with her righteous fury and immortalizing the principle that divine justice punishes unjust rulers.",
        "date_order": 450,
        "date_label": "c. 5th Century CE",
        "era": "Classical Era",
        "region": "Poompuhar, Madurai & Vanci",
        "period": "Post-Sangam Epic Era",
        "location_name": "Poompuhar Maritime Heritage Coast",
        "latitude": 11.1444,
        "longitude": 79.8556,
        "image_url": "/assets/history/silappatikaram-epic.jpg",
        "image_caption": "Artistic depiction of Kannagi demanding justice at the Pandyan Court",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1276701) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1276701",
        "license": "CC BY-SA 4.0",
        "tags": "history,epic,silappatikaram,kannagi,ilango",
        "related_slugs": "thirukkural-composition,kalabhra-period-epics",
    },
    {
        "slug": "kalabhra-period-epics",
        "content_type": "history",
        "title_ta": "சங்கம் மருவிய காலம் மற்றும் களப்பிரர் ஆட்சியின் இலக்கியங்கள்",
        "title_en": "Post-Sangam & Kalabhra Era Scholarly Epics",
        "category": "History",
        "summary_ta": "சமணர் மற்றும் பௌத்த அறிஞர்கள் சீவக சிந்தாமணி, மணிமேகலை மற்றும் பதினெண்கீழ்க்கணக்கு நூல்களை இயற்றிய காலம்.",
        "summary_en": "Era of Jain and Buddhist literary patronage giving rise to ethical masterpieces like Manimekalai and Seevaga Chinthamani.",
        "content_ta": "கி.பி. 3 முதல் 6-ஆம் நூற்றாண்டு வரையிலான சங்கம் மருவிய காலத்தில் சமண மற்றும் பௌத்த அறிஞர்கள் பெரும் இலக்கியத் தொண்டாற்றினார்கள். சீத்தலைச் சாத்தனார் இயற்றிய 'மணிமேகலை', திருத்தக்கதேவர் இயற்றிய 'சீவக சிந்தாமணி' மற்றும் அறநூல்களான 'நாலடியார்', 'நான்மணிக்கடிகை' போன்றவை இக்காலத்தில் இயற்றப்பட்டன. இது தமிழ் மொழியில் அறக்கோட்பாடுகளையும் தத்துவ விவாதங்களையும் வளர்த்தெடுத்தது.",
        "content_en": "Spanning the 3rd to 6th centuries CE, the Post-Sangam period was marked by rich Jain and Buddhist academic patronage. Buddhist scholar Sithalai Sathanar authored Manimekalai (exploring Buddhist philosophy and social service), while Jain monk Tirutakkatevar composed Seevaga Chinthamani. This era also saw the compilation of the Pathinenkilkanakku ethical treatises, shaping moral philosophy in Tamil culture.",
        "date_order": 500,
        "date_label": "c. 300 – 600 CE",
        "era": "Classical Era",
        "region": "Tamilakam",
        "period": "Post-Sangam Era",
        "location_name": "Kanchipuram & Kaveripattinam Academies",
        "latitude": 12.8342,
        "longitude": 79.7036,
        "image_url": "/assets/history/kalabhra-period.jpg",
        "image_caption": "Palm-leaf scroll collections of Post-Sangam ethical literature",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534002) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534002",
        "license": "CC BY-SA 4.0",
        "tags": "history,kalabhra,jain,buddhism,manimekalai",
        "related_slugs": "silappatikaram-epic,pallava-rock-cut-architecture",
    },

    # ---------------------------------------------------------------- Pallava Period
    {
        "slug": "kanchi-ghatika-learning",
        "content_type": "history",
        "title_ta": "காஞ்சி கடிகை மற்றும் சர்வதேசக் கல்வி மையம்",
        "title_en": "Kanchipuram Ghatika & Ancient International Academy",
        "category": "History",
        "summary_ta": "பல்லவர் காலத்தில் சர்வதேச அறிஞர்களையும் தத்துவவாதிகளையும் ஈர்த்த காஞ்சி கடிகை பல்கலைக்கழகம்.",
        "summary_en": "The famous Ghatika of Kanchipuram flourishes as South Asia's premier university attracting scholars like Xuanzang and Bodhidharma.",
        "content_ta": "பல்லவர் தலைநகரான காஞ்சிபுரம் பண்டைய தென்னாசியாவின் புகழ்பெற்ற சர்வதேசக் கல்வி மையமாக ('கடிகை') விளங்கியது. வடமொழி, தமிழ், பௌத்த தத்துவம், நியாய தர்க்கம் மற்றும் மருத்துவக் கலைகள் இங்கு கற்பிக்கப்பட்டன. பௌத்த துறவி போதிதர்மர் மற்றும் நியாய தர்க்க அறிஞர் தின்னாகர் இங்கிருந்து உருவானவர்கள். சீனப் பயணி யுவான் சுவாங் (Hiuen Tsang) கி.பி. 640-இல் காஞ்சிக்கு வருகை தந்து இங்குள்ள 100-க்கும் மேற்பட்ட பௌத்த விகாரைகளையும் கல்வி மேன்மையையும் பாராட்டி எழுதியுள்ளார்.",
        "content_en": "Under Pallava patronage, Kanchipuram established the 'Ghatika'—a prestigious university center drawing scholars from across India, East Asia, and Sri Lanka. Subjects included Tamil linguistics, Sanskrit epics, logic (Nyaya), and Buddhist philosophy. It produced legendary scholars such as Buddhist logician Dinnaga and Zen founder Bodhidharma. Chinese traveler Xuanzang visited Kanchi in 640 CE, leaving vivid records of its vibrant intellectual ecosystem.",
        "date_order": 640,
        "date_label": "c. 400 – 700 CE",
        "era": "Pallava Period",
        "region": "Kanchipuram",
        "period": "Pallava Educational Era",
        "location_name": "Ancient Kanchipuram Ghatika Center",
        "latitude": 12.8342,
        "longitude": 79.7036,
        "image_url": "/assets/history/kanchi-ghatika.jpg",
        "image_caption": "Historic temple precinct of Kanchipuram, ancient seat of learning",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1526435) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1526435",
        "license": "CC BY-SA 4.0",
        "tags": "history,kanchipuram,ghatika,bodhidharma,pallava",
        "related_slugs": "pallava-rock-cut-architecture,bhakti-movement-renaissance",
    },
    {
        "slug": "pallava-rock-cut-architecture",
        "content_type": "history",
        "title_ta": "பல்லவர்களின் குடைவரைக் கட்டிடக்கலை",
        "title_en": "Architectural Golden Era of the Pallavas",
        "category": "History",
        "summary_ta": "முதலாம் நரசிம்மவர்மனின் ஆட்சியில் மாமல்லபுரத்தில் பாறை குடைவரைகளும் கடற்கரைக் கோவிலும் உருவாவது.",
        "summary_en": "King Narasimhavarman I transforms rock cliffs at Mamallapuram into monolithic temples and shore monuments.",
        "content_ta": "கி.பி. 7-ஆம் நூற்றாண்டில் பல்லவ மன்னர்களான மகேந்திரவர்மன் மற்றும் முதலாம் நரசிம்மவர்மன் (மாமல்லன்) காலத்தில் திராவிடக் கட்டிடக்கலை புதிய பரிமாணம் பெற்றது. பாறைகளை மரத்தைப் போல் குடைந்து கோவில்களையும் சிற்பங்களையும் செதுக்கினார்கள். மாமல்லபுரத்தின் பஞ்ச ரதங்கள், அர்ஜுனன் தபஸ் சிற்பம் மற்றும் கடற்கரைக் கோவில் ஆகியவை பல்லவர் கலைத்திறனுக்குச் சான்றுகளாகும்.",
        "content_en": "During the 7th century CE, Pallava monarchs Mahendravarman I and Narasimhavarman I (Mamalla) pioneered monolithic rock-cut architecture in South India. They carved entire granite hills into cave temples, monolithic chariots (Pancha Rathas), and open-air relief panels at Mamallapuram, laying the architectural foundations for later Dravidian temple structures.",
        "date_order": 650,
        "date_label": "c. 630 – 728 CE",
        "era": "Pallava Period",
        "region": "Kanchipuram & Mamallapuram",
        "period": "Pallava Dynasty",
        "location_name": "Mamallapuram Monolithic Complex, Chengalpattu",
        "latitude": 12.6169,
        "longitude": 80.1927,
        "image_url": "/assets/history/pallava-architecture.jpg",
        "image_caption": "Pallava Shore Temple carved at Mamallapuram along the Coromandel coast",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1526435) & UNESCO",
        "source_url": "https://www.wikidata.org/wiki/Q1526435",
        "license": "CC BY-SA 4.0",
        "tags": "history,pallava,mamallapuram,architecture,kanchipuram",
        "related_slugs": "kanchi-ghatika-learning,bhakti-movement-renaissance",
    },
    {
        "slug": "bhakti-movement-renaissance",
        "content_type": "history",
        "title_ta": "தமிழ் பக்தி இயக்க எழுச்சி",
        "title_en": "The Tamil Bhakti Movement",
        "category": "History",
        "summary_ta": "நாயன்மார்களும் ஆழ்வார்களும் தேவாரம், திவ்யப்பிரபந்தம் இசைப் பாடல்கள் மூலம் தமிழை வளர்த்த காலம்.",
        "summary_en": "Nayanmars and Alvars compose soul-stirring devotional music (Tevaram & Divya Prabandham), democratizing spirituality and Tamil literature.",
        "content_ta": "கி.பி. 6 முதல் 9-ஆம் நூற்றாண்டு வரை தமிழ்நாட்டில் பக்தி இயக்கம் உச்சம்பெற்றது. 63 நாயன்மார்களும் (அப்பர், சம்பந்தர், சுந்தரர், மாணிக்கவாசகர்) 12 ஆழ்வார்களும் (ஆண்டாள், நம்மாழ்வார் உள்ளிட்டோர்) ஊர் ஊராகச் சென்று தமிழில் பண்ணிசையோடு பாடல்களைப் பாடினார்கள். தேவாரம் மற்றும் நாலாயிர திவ்வியப் பிரபந்தம் போன்ற பக்தி இலக்கியங்கள் தமிழ் மொழியையும் இசையையும் மக்களிடையே பரப்பின.",
        "content_en": "Spanning the 6th to 9th centuries CE, the Tamil Bhakti Movement produced a cultural renaissance. 63 Shaivite Nayanmars and 12 Vaishnavite Alvars traversed South India composing divine poetry set to classical Tamil Pan music. Their works—collected in the Tevaram and Nalayira Divya Prabandham—dismantled social barriers and transformed Tamil into a vessel of accessible spiritual devotion.",
        "date_order": 750,
        "date_label": "c. 600 – 900 CE",
        "era": "Pallava Period",
        "region": "Tamilakam",
        "period": "Bhakti Era",
        "location_name": "Chidambaram & Srirangam Temple Belt, Tiruchirappalli",
        "latitude": 10.8622,
        "longitude": 78.6897,
        "image_url": "/assets/history/bhakti-movement.jpg",
        "image_caption": "Devotional Pan music and temple bronze heritage of the Bhakti movement",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q324083) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q324083",
        "license": "CC BY-SA 4.0",
        "tags": "history,bhakti,tevaram,alvar,nayanmar",
        "related_slugs": "pallava-rock-cut-architecture,rajaraja-brihadisvara",
    },

    # ---------------------------------------------------------------- Imperial Chola Empire
    {
        "slug": "chola-rise-vijayalaya",
        "content_type": "history",
        "title_ta": "விஜயாலய சோழன் ஆட்சியில் சோழர் மறுமலர்ச்சி",
        "title_en": "Re-establishment of the Imperial Chola Dynasty",
        "category": "History",
        "summary_ta": "கி.பி. 850-இல் விஜயாலய சோழன் தஞ்சாவூரைக் கைப்பற்றி பிற்கால சோழப் பேரரசிற்கு அடிக்கல் நாட்டியது.",
        "summary_en": "Vijayalaya Chola captures Thanjavur in 850 CE, laying the foundation for the Imperial Chola Empire.",
        "content_ta": "கி.பி. 850-இல் விஜயாலய சோழன் முத்தரையர்களிடமிருந்து தஞ்சாவூரைக் கைப்பற்றி சோழர்களின் தலைநகரமாக மாற்றினார். இது பிற்காலச் சோழப் பேரரசின் எழுச்சிக்கு தொடக்கமாக அமைந்தது. தஞ்சாவூரில் நிசும்பசூதனி கோவிலைக் கட்டி சோழர்களின் புதிய சாம்ராஜ்யத்தை நிறுவினார். இவருக்குப் பின் வந்த ஆதித்ய சோழனும் பராந்தக சோழனும் பேரரசை விரிவுபடுத்தினார்கள்.",
        "content_en": "In 850 CE, Vijayalaya Chola captured Thanjavur from the Muttaraiyar chieftains, establishing it as the strategic imperial capital of the Cholas. This marked the dramatic resurgence of the Medieval Cholas. Vijayalaya's descendants—Aditya I and Parantaka I—expanded the empire across the Kaveri basin, paving the way for the golden era of Raja Raja Chola I.",
        "date_order": 850,
        "date_label": "850 CE",
        "era": "Chola Empire",
        "region": "Thanjavur, Kaveri Delta",
        "period": "Imperial Chola Dynasty",
        "location_name": "Thanjavur Chola Fort, Kaveri Delta",
        "latitude": 10.7870,
        "longitude": 79.1378,
        "image_url": "/assets/history/chola-rise.jpg",
        "image_caption": "Imperial Chola royal emblem and Thanjavur fort heritage",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q151148) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q151148",
        "license": "CC BY-SA 4.0",
        "tags": "history,chola,vijayalaya,thanjavur,empire",
        "related_slugs": "rajaraja-brihadisvara,rajendra-chola-expedition",
    },
    {
        "slug": "rajaraja-brihadisvara",
        "content_type": "history",
        "title_ta": "முதலாம் ராஜராஜ சோழன் மற்றும் தஞ்சைப் பெரிய கோவில்",
        "title_en": "Raja Raja Chola I & Consecration of Brihadisvara Temple",
        "category": "History",
        "summary_ta": "கி.பி. 1010-இல் முதலாம் ராஜராஜ சோழன் தஞ்சாவூர் பிரகதீஸ்வரர் கோவிலைக் கட்டி கும்பாபிஷேகம் செய்தது.",
        "summary_en": "Emperor Raja Raja Chola I completes construction of the 216-foot granite Brihadisvara Temple in 1010 CE.",
        "content_ta": "முதலாம் ராஜராஜ சோழன் (கி.பி. 985-1014) சோழப் பேரரசின் தலைசிறந்த மன்னராவார். இவர் கி.பி. 1010-இல் தஞ்சாவூர் பெரிய கோவிலைக் கட்டி முடித்தார். இக்கோவிலின் சுவர்களில் நில அளவை, வரி முறை, கிராமக் குடவோலைத் தேர்தல் முறை மற்றும் கோவில் ஊழியர்களின் பெயர்கள் கல்வெட்டுகளாகச் செதுக்கப்பட்டுள்ளன. இவருடைய ஆட்சியில் தமிழ்நாட்டின் பொருளாதாரம், கலை மற்றும் நிர்வாகம் உச்சியை அடைந்தது.",
        "content_en": "Emperor Raja Raja Chola I (reigned 985–1014 CE) was an exceptional military strategist, administrator, and patron of arts. In 1010 CE, he consecrated the magnificent 216-foot granite Brihadisvara Temple. Beyond architecture, his reign introduced computerized land surveys, transparent Kudavolai electoral balloting, and meticulously detailed stone epigraphs detailing kingdom revenue.",
        "date_order": 1010,
        "date_label": "1010 CE",
        "era": "Chola Empire",
        "region": "Thanjavur",
        "period": "Chola Golden Age",
        "location_name": "Thanjavur Brihadisvara Temple Site",
        "latitude": 10.7828,
        "longitude": 79.1318,
        "image_url": "/assets/history/brihadisvara-temple.jpg",
        "image_caption": "Vimana of Brihadisvara Temple built by Raja Raja Chola I in 1010 CE",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q667794) & UNESCO",
        "source_url": "https://www.wikidata.org/wiki/Q667794",
        "license": "CC BY-SA 4.0",
        "tags": "history,chola,rajaraja,thanjavur,brihadisvara",
        "related_slugs": "chola-rise-vijayalaya,rajendra-chola-expedition",
    },
    {
        "slug": "rajendra-chola-expedition",
        "content_type": "history",
        "title_ta": "முதலாம் ராஜேந்திர சோழனின் கங்கைகொண்ட சோழபுரம் மற்றும் கடற்படை வெற்றிகள்",
        "title_en": "Rajendra Chola I: Northern Expedition & Southeast Asian Naval Conquest",
        "category": "History",
        "summary_ta": "கங்கை வரை படைசெடுத்து கங்கைகொண்ட சோழபுரத்தை நிறுவி, ஸ்ரீவிஜயப் பேரரசை (இந்தோனேசியா) வென்ற கடற்படை வெற்றி.",
        "summary_en": "Rajendra Chola I conquers up to the Ganges River and launches an unprecedented overseas naval campaign across Southeast Asia (1025 CE).",
        "content_ta": "ராஜராஜ சோழனின் மகனான முதலாம் ராஜேந்திர சோழன் (கி.பி. 1014-1044) வடஇந்தியாவின் கங்கை நதி வரை படைசெடுத்து வெற்றி பெற்று 'கங்கைகொண்ட சோழன்' என்று பட்டம் பெற்றார். இதன் நினைவாக கங்கைகொண்ட சோழபுரத்தை புதிய தலைநகராக உருவாக்கினார். கி.பி. 1025-இல் சோழர் கடற்படையைக் கொண்டு கடாரம் (மலேசியா) மற்றும் ஸ்ரீவிஜயம் (இந்தோனேசியா, சுமத்ரா) ஆகிய நாடுகளை வென்று வங்காள விரிகுடாவை 'சோழர்களின் ஏரி'யாக மாற்றினார்.",
        "content_en": "Rajendra Chola I (reigned 1014–1044 CE) expanded Chola glory to unprecedented geographic scales. He led an expedition north to the Ganges River, founding the magnificent new capital Gangaikonda Cholapuram. In 1025 CE, he launched a massive trans-oceanic naval invasion against Sri Vijaya (modern Sumatra, Malaysia, and Thailand), securing trade routes across the Malacca Strait and turning the Bay of Bengal into a 'Chola Lake'.",
        "date_order": 1025,
        "date_label": "1025 CE",
        "era": "Chola Empire",
        "region": "Gangaikonda Cholapuram & Southeast Asia",
        "period": "Chola Naval Conquests",
        "location_name": "Gangaikondacholapuram Capital Site, Ariyalur",
        "latitude": 11.2064,
        "longitude": 79.4485,
        "image_url": "/assets/history/chola-naval-expedition.jpg",
        "image_caption": "Imperial Chola naval fleet depiction and Gangaikonda Cholapuram temple",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q151148) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q151148",
        "license": "CC BY-SA 4.0",
        "tags": "history,chola,rajendra,navy,maritime,gangaikonda",
        "related_slugs": "rajaraja-brihadisvara,chola-bronze-casting",
    },
    {
        "slug": "chola-bronze-casting",
        "content_type": "history",
        "title_ta": "சோழர்களின் வெண்கலச் சிற்பக் கலைப் பொற்காலம்",
        "title_en": "Golden Era of Chola Bronze Sculpting",
        "category": "History",
        "summary_ta": "மெழுகு உருக்கல் முறையில் (Lost-Wax Process) ஆனந்த நடராஜர் மற்றும் தெய்வங்களின் வெண்கலச் சிற்பங்கள் வார்க்கப்பட்ட காலகட்டம்.",
        "summary_en": "Chola artisans achieve world-renowned bronze sculpting mastery using the lost-wax technique, creating iconic Nataraja bronzes.",
        "content_ta": "சோழர் ஆட்சிக் காலத்தில் (10 முதல் 12-ஆம் நூற்றாண்டு) வெண்கலச் சிற்பக் கலை உலகளவில் உச்சம்பெற்றது. 'மெழுகு உருக்கல் முறை' (Cire Perdue / Lost-Wax Technique) பயன்படுத்தி நடராஜர், சிவகாமி, போகசக்தி மற்றும் அறுபத்து மூவர் வெண்கலச் சிலைகள் வார்க்கப்பட்டன. இச்சிலைகளின் விகிதாச்சாரம், வளைவுகள் மற்றும் நுணுக்கமான வேலைப்பாடுகள் சர்வதேச அருங்காட்சியகங்களில் இன்றளவும் இந்தியாவின் சிறந்த கலைப் படைப்புகளாகக் போற்றப்படுகின்றன.",
        "content_en": "During the 10th to 12th centuries CE, Chola metallurgists attained unmatched perfection in bronze casting using the lost-wax process (Cire Perdue). Creating fluid masterpieces such as Nataraja (Lord of Cosmic Dance), Parvati, and saints, these bronzes captured dynamic motion and spiritual grace. Leading art historians worldwide acknowledge Chola bronzes as peak achievements of human metallurgic sculpture.",
        "date_order": 1100,
        "date_label": "c. 10th – 12th Century CE",
        "era": "Chola Empire",
        "region": "Swamimalai & Thanjavur",
        "period": "Chola Metallurgical Era",
        "location_name": "Swamimalai Bronze Artisan Heritage Center",
        "latitude": 10.9575,
        "longitude": 79.3242,
        "image_url": "/assets/history/chola-bronze.jpg",
        "image_caption": "Iconic Chola Nataraja bronze icon created using the lost-wax technique",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q151148) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q151148",
        "license": "CC BY-SA 4.0",
        "tags": "history,chola,bronze,nataraja,art,sculpture",
        "related_slugs": "rajaraja-brihadisvara,rajendra-chola-expedition",
    },

    # ---------------------------------------------------------------- Pandya & Nayak Kingdoms
    {
        "slug": "pandyan-revival-maravarman",
        "content_type": "history",
        "title_ta": "மாறவர்மன் சுந்தரபாண்டியனின் பாண்டியப் பேரரசு மறுமலர்ச்சி",
        "title_en": "Pandyan Empire Revival under Maravarman Sundara Pandyan",
        "category": "History",
        "summary_ta": "13-ஆம் நூற்றாண்டில் பாண்டியர்கள் சோழர்களை வென்று மதுரையை மீண்டும் தென்னிந்தியாவின் முதன்மை தலைநகராக மாற்றியது.",
        "summary_en": "Pandyan resurgence in 1216 CE under Maravarman Sundara Pandyan I, re-establishing Madurai as a dominant power.",
        "content_ta": "கி.பி. 13-ஆம் நூற்றாண்டில் மாறவர்மன் சுந்தரபாண்டியன் I ஆட்சியில் பாண்டியப் பேரரசு மீண்டும் மாபெரும் சக்தியாக எழுச்சி பெற்றது. சோழர்களை வென்று தஞ்சாவூரையும் உறையூரையும் பாண்டியக் கொடியின் கீழ் கொண்டுவந்தார். இவருக்குப் பின் வந்த சடையவர்மன் சுந்தரபாண்டியன் I ஆட்சியில் பாண்டியப் பேரரசு நெல்லூர் முதல் இலங்கை வரை பரவியது. மதுரை மீண்டும் தென்னிந்தியாவின் கலை மற்றும் வணிகத் தலைநகராகத் திகழ்ந்தது.",
        "content_en": "In 1216 CE, Maravarman Sundara Pandyan I sparked the Second Pandyan Empire by defeating the weakening Cholas and re-establishing Madurai as the political hub of South India. Under his successor Jatavarman Sundara Pandyan I (reigned 1251–1268 CE), the kingdom expanded from Nellore to northern Sri Lanka, controlling lucrative pearl fisheries and international sea trade.",
        "date_order": 1216,
        "date_label": "1216 – 1268 CE",
        "era": "Pandya Kingdom",
        "region": "Madurai & Korkai",
        "period": "Second Pandyan Empire",
        "location_name": "Madurai Pandyan Capital Citadel",
        "latitude": 9.9195,
        "longitude": 78.1193,
        "image_url": "/assets/history/pandyan-revival.jpg",
        "image_caption": "Gopuram towers of Madurai expanded during the Second Pandyan Empire",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534002) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534002",
        "license": "CC BY-SA 4.0",
        "tags": "history,pandya,madurai,sundarapandyan,empire",
        "related_slugs": "madurai-nayak-kingdom,sangam-assembly-foundations",
    },
    {
        "slug": "madurai-nayak-kingdom",
        "content_type": "history",
        "title_ta": "திருமலை நாயக்கர் மற்றும் மதுரை நாயக்கர் ஆட்சி",
        "title_en": "Thirumalai Nayak & The Madurai Nayak Dynasty",
        "category": "History",
        "summary_ta": "17-ஆம் நூற்றாண்டில் மதுரை திருமலை நாயக்கர் மஹால் கட்டப்படுதலும், மீனாட்சி கோவில் கோபுரங்கள் விரிவாக்கமும்.",
        "summary_en": "Reign of King Thirumalai Nayak (1623–1659 CE), famed for constructing Thirumalai Nayak Mahal and expanding Meenakshi Temple.",
        "content_ta": "மதுரை நாயக்கர் வம்சத்தின் மிகவும் புகழ்பெற்ற மன்னர் திருமலை நாயக்கர் (கி.பி. 1623-1659) ஆவார். இவர் மதுரையில் இத்தாலிய மற்றும் திராவிட கட்டிடக்கலை பாணிகள் இணைந்த 'திருமலை நாயக்கர் மஹால்' அரண்மனையைக் கட்டினார். மதுரை மீனாட்சி அம்மன் கோவிலின் பிரம்மாண்ட புதுமண்டபம், ஆயிரங்கால் மண்டப விரிவாக்கம் மற்றும் ராஜகோபுரங்களைப் புதுப்பித்து மதுரையை கலை நகரமாக மாற்றினார்.",
        "content_en": "King Thirumalai Nayak (reigned 1623–1659 CE) was the greatest ruler of the Madurai Nayak Dynasty. He constructed the architectural marvel Thirumalai Nayak Mahal, blending Italian Indo-Saracenic features with traditional Dravidian design. He also constructed the Pudhumandapam and elevated the towering Gopurams of the Madurai Meenakshi Temple.",
        "date_order": 1623,
        "date_label": "1623 – 1659 CE",
        "era": "Pandya Kingdom",
        "region": "Madurai",
        "period": "Nayak Kingdom",
        "location_name": "Thirumalai Nayak Mahal, Madurai",
        "latitude": 9.9172,
        "longitude": 78.1228,
        "image_url": "/assets/history/thirumalai-nayak-mahal.jpeg",
        "image_caption": "Grand Indo-Saracenic pillars of Thirumalai Nayak Mahal in Madurai",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1427510) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1427510",
        "license": "CC BY-SA 4.0",
        "tags": "history,nayak,madurai,thirumalai,architecture",
        "related_slugs": "pandyan-revival-maravarman,thanjavur-maratha-saraswathi-mahal",
    },
    {
        "slug": "thanjavur-maratha-saraswathi-mahal",
        "content_type": "history",
        "title_ta": "தஞ்சாவூர் மராத்தியர் ஆட்சி மற்றும் சரஸ்வதி மகால் நூலக வளர்ச்சி",
        "title_en": "Thanjavur Maratha Dynasty & Saraswathi Mahal Library Expansion",
        "category": "History",
        "summary_ta": "இரண்டாம் சரபோஜி மன்னர் காலத்தில் சரஸ்வதி மகால் நூலகம் உலகளவில் புகழ்பெற்ற சுவடி சேகரிப்பாக மேம்படுத்தப்பட்ட காலகட்டம்.",
        "summary_en": "Serfoji II transforms Thanjavur's Saraswathi Mahal Library into an internationally acclaimed repository of palm-leaf manuscripts.",
        "content_ta": "தஞ்சாவூர் மராத்திய மன்னர் இரண்டாம் சரபோஜி (கி.பி. 1798-1832) கலை, மருத்துவம் மற்றும் கல்வியில் பெரும் புரட்சி செய்தார். இவரது ஆதரவில் தஞ்சாவூர் சரஸ்வதி மகால் நூலகம் உலகின் மிகத் தொன்மையான சுவடி நூலகங்களில் ஒன்றாக உருவெடுத்தது. தமிழ், தெலுங்கு, மராத்தி மற்றும் சமஸ்கிருத மொழிகளில் உள்ள 60,000-க்கும் மேற்பட்ட ஓலைச்சுவடிகளும், ஆயுர்வேத சித்தா மருத்துவக் குறிப்புகளும், மேலைநாட்டு அறிவியல் புத்தகங்களும் இங்கு பாதுகாக்கப்பட்டன.",
        "content_en": "King Serfoji II (reigned 1798–1832 CE) of the Thanjavur Maratha dynasty was a visionary polymath who expanded the Tanjore Maharaja Serfoji's Saraswathi Mahal Library into one of Asia's oldest operating manuscript libraries. He amassed over 60,000 rare palm-leaf and paper manuscripts on Tamil medicine (Siddha), astronomy, music, literature, and European printing presses.",
        "date_order": 1798,
        "date_label": "c. 1798 – 1832 CE",
        "era": "Pandya Kingdom",
        "region": "Thanjavur",
        "period": "Thanjavur Maratha Era",
        "location_name": "Saraswathi Mahal Library, Thanjavur Palace",
        "latitude": 10.7905,
        "longitude": 79.1381,
        "image_url": "/assets/history/saraswathi-mahal.jpg",
        "image_caption": "Historic Saraswathi Mahal Library manuscript hall in Thanjavur Palace",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q151148) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q151148",
        "license": "CC BY-SA 4.0",
        "tags": "history,maratha,serfoji,thanjavur,saraswathimahal,library",
        "related_slugs": "madurai-nayak-kingdom,rajaraja-brihadisvara",
    },

    # ---------------------------------------------------------------- Colonial Era & Freedom Movement
    {
        "slug": "veerapandiya-kattabomman",
        "content_type": "history",
        "title_ta": "வீரபாண்டிய கட்டபொம்மனின் சுதந்திரப் போராட்டம்",
        "title_en": "Veerapandiya Kattabomman's Anti-Colonial Resistance",
        "category": "History",
        "summary_ta": "1799-இல் கிழக்கிந்திய கம்பெனியின் வரி விதிப்புக்கு எதிராகப் பாஞ்சாலங்குறிச்சியில் நடைபெற்ற வீரம் நிறைந்த எதிர்ப்பு.",
        "summary_en": "18th-century Palayakkarar chieftain of Panchalankurichi who led armed resistance against British East India Company taxation (1799).",
        "content_ta": "பாஞ்சாலங்குறிச்சியின் பாளையக்காரரான வீரபாண்டிய கட்டபொம்மன் (1760-1799) பிரிட்டிஷ் கிழக்கிந்திய கம்பெனியின் ஆதிக்கத்திற்கு எதிராக வீரம் செறிந்த எதிர்ப்பை வெளிப்படுத்தினார். 'வானம் பொழிகிறது, பூமி விளைகிறது, உனக்கு ஏன் கொடுப்பது வரி?' என்ற இவரது எதிர்ப்பு உரை இந்திய சுதந்திர வரலாற்றில் புகழ்பெற்றது. 1799 அக்டோபர் 16 அன்று கயத்தாறில் தூக்கிலிடப்பட்டார்.",
        "content_en": "Veerapandiya Kattabomman (1760–1799) was the Palayakkarar chieftain of Panchalankurichi who spearheaded early armed resistance against British East India Company hegemony. Refusing to pay land tax to foreign rulers, his defiant confrontation with Collector Jackson remains a celebrated moment in Tamil anti-colonial history. He was captured and executed at Kayathar on October 16, 1799.",
        "date_order": 1799,
        "date_label": "1799 CE",
        "era": "Colonial Era",
        "region": "Panchalankurichi & Kayathar",
        "period": "Polygar Wars",
        "location_name": "Panchalankurichi Fort, Thoothukudi",
        "latitude": 8.9083,
        "longitude": 78.0083,
        "image_url": "/assets/history/kattabomman.jpg",
        "image_caption": "Historic Panchalankurichi memorial fort commemorating Kattabomman",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534575) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534575",
        "license": "CC BY-SA 4.0",
        "tags": "history,kattabomman,freedom,anti-colonial,panchalankurichi",
        "related_slugs": "voc-swadeshi-shipping,bharati-nationalist-poetry",
    },
    {
        "slug": "voc-swadeshi-shipping",
        "content_type": "history",
        "title_ta": "வ.உ.சிதம்பரனாரின் சுதேசி நாவாய்ச் சங்கம்",
        "title_en": "V.O. Chidambaram Pillai & Swadeshi Steam Navigation Company",
        "category": "History",
        "summary_ta": "1906-இல் ஆங்கிலேயர் கப்பல் ஏகபோகத்தை உடைக்க கப்பலோட்டிய தமிழன் வ.உ.சி உருவாக்கிய சுதேசி கப்பல் நிறுவனம்.",
        "summary_en": "In 1906, 'Kappalottiya Thamilan' V.O. Chidambaram Pillai launches India's first swadeshi shipping fleet to challenge British maritime monopoly.",
        "content_ta": "சுதந்திரப் போராட்ட வீரர் 'கப்பலோட்டிய தமிழன்' வ.உ.சிதம்பரனார் (1872-1936) 1906 அக்டோபர் 16 அன்று தூத்துக்குடியில் 'சுதேசி நாவாய்ச் சங்கம்' (Swadeshi Steam Navigation Company) என்ற இந்திய கப்பல் நிறுவனத்தைத் தொடங்கினார். 'எஸ்.எஸ். காலியா', 'எஸ்.எஸ். லாவோ' ஆகிய இரண்டு சுதேசிக் கப்பல்களை வாங்கி தூத்துக்குடி-கொழும்பு இடையே இயக்கினார். இதன் மூலம் பிரிட்டிஷ் கப்பல் ஏகபோகத்தை உடைத்து சுதேசிப் பொருளாதாரப் புரட்சியை ஏற்படுத்தினார்.",
        "content_en": "Freedom fighter 'Kappalottiya Thamilan' V.O. Chidambaram Pillai (1872–1936) founded the Swadeshi Steam Navigation Company on October 16, 1906, in Tuticorin. Purchasing two steamships—S.S. Gaelia and S.S. Lawoe—he established regular passenger and cargo maritime service between Tuticorin and Colombo, breaking the oppressive British India Steam Navigation monopoly and pioneering India's commercial freedom movement.",
        "date_order": 1906,
        "date_label": "October 16, 1906 CE",
        "era": "Colonial Era",
        "region": "Thoothukudi (Tuticorin) & Colombo",
        "period": "Swadeshi Movement",
        "location_name": "V.O. Chidambaranar Port, Thoothukudi",
        "latitude": 8.7523,
        "longitude": 78.1812,
        "image_url": "/assets/history/voc-swadeshi-ship.jpg",
        "image_caption": "Historic Swadeshi steamship vessel launched by V.O. Chidambaram Pillai in 1906",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3535496) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3535496",
        "license": "CC BY-SA 4.0",
        "tags": "history,voc,swadeshi,shipping,freedom,tuticorin",
        "related_slugs": "veerapandiya-kattabomman,bharati-nationalist-poetry",
    },
    {
        "slug": "bharati-nationalist-poetry",
        "content_type": "history",
        "title_ta": "மகாகவி சுப்பிரமணிய பாரதியாரின் மறுமலர்ச்சிக் கவிதைகள்",
        "title_en": "Mahakavi Subramania Bharati's Literary & Social Renaissance",
        "category": "History",
        "summary_ta": "சுதந்திர தாகம், பெண் விடுதலை மற்றும் சமத்துவத்தை வலியுறுத்தி நவீன தமிழை உருவாக்கிய மகாகவியின் காலம்.",
        "summary_en": "Mahakavi Bharathiyar (1882–1921) revolutionizes modern Tamil poetry, championing Indian independence, women's liberation, and caste abolition.",
        "content_ta": "மகாகவி சுப்பிரமணிய பாரதியார் (1882-1921) நவீன தமிழ் இலக்கியத்தின் பிதாமகன் ஆவார். 'அச்சமில்லை அச்சமில்லை', 'வந்தே மாதரம்' போன்ற நாட்டுப்பற்றுப் பாடல்கள் மூலம் இந்திய சுதந்திரப் போராட்டத்திற்குப் புத்துயிர் ஊட்டினார். பெண் விடுதலை, சாதி ஒழிப்பு மற்றும் சமூகச் சமத்துவத்தை வலியுறுத்தி எளிய தமிழில் பாமரனுக்கும் புரியும் கவிதைகளைப் படைத்தார்.",
        "content_en": "Subramania Bharati (1882–1921), universally revered as Mahakavi ('Great Poet'), pioneered modern Tamil prose and free verse. Through fiery patriotic anthems like 'Achamillai Achamillai' and 'Vande Matharam', he ignited the freedom struggle while advocating radical gender equality, caste abolition, and universal education in accessible Tamil.",
        "date_order": 1908,
        "date_label": "1882 – 1921 CE",
        "era": "Colonial Era",
        "region": "Ettayapuram, Puducherry & Chennai",
        "period": "Tamil Renaissance",
        "location_name": "Ettayapuram Bharati Heritage Residence, Thoothukudi",
        "latitude": 9.1500,
        "longitude": 77.9833,
        "image_url": "/assets/history/bharati-rennaisance.jpg",
        "image_caption": "Literary manuscripts and portrait of Mahakavi Subramania Bharati",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q312480) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q312480",
        "license": "CC BY-SA 4.0",
        "tags": "history,bharati,poet,freedom,rennaisance",
        "related_slugs": "voc-swadeshi-shipping,thirukkural-composition",
    },

    # ---------------------------------------------------------------- Modern Era
    {
        "slug": "reorganization-tamil-nadu",
        "content_type": "history",
        "title_ta": "மெட்ராஸ் மாநிலத்திற்கு 'தமிழ்நாடு' எனப் பெயர் மாற்றம் பெறல்",
        "title_en": "Official Naming of 'Tamil Nadu' State (1969)",
        "category": "History",
        "summary_ta": "1969 ஜனவரி 14 அன்று மெட்ராஸ் மாநிலம் உத்தியோகபூர்வமாக 'தமிழ்நாடு' என்று பெயர் மாற்றம் பெற்றது.",
        "summary_en": "Chief Minister C.N. Annadurai officially renames Madras State to 'Tamil Nadu' on January 14, 1969.",
        "content_ta": "1967-இல் ஆட்சி அமைத்த முதலமைச்சர் பேரறிஞர் சி.என். அண்ணாதுரை தலைமையிலான அரசு, சென்னை சட்டமன்றத்தில் மெட்ராஸ் மாநிலத்தை 'தமிழ்நாடு' என்று பெயர் மாற்றுவதற்கான வரலாற்றுச் சிறப்புமிக்க தீர்மானத்தைக் கொண்டுவந்தது. பாராளுமன்ற ஒப்புதலுக்குப் பின் 1969 ஜனவரி 14 அன்று 'தமிழ்நாடு' என்ற பெயர் அதிகாரப்பூர்வமாக நடைமுறைக்கு வந்தது. தியாகி சங்கரலிங்கனாரின் தியாகமும் இதில் குறிப்பிடத்தக்கது.",
        "content_en": "On July 18, 1967, Chief Minister C.N. Annadurai introduced a landmark resolution in the State Assembly to rename Madras State to 'Tamil Nadu' ('Land of Tamils'), fulfilling a long-standing democratic demand championed by martyrs like Sankaralinganar. Following Parliamentary approval, the renaming officially took effect on January 14, 1969.",
        "date_order": 1969,
        "date_label": "January 14, 1969 CE",
        "era": "Modern Era",
        "region": "Chennai, Tamil Nadu",
        "period": "Modern Democratic Era",
        "location_name": "Fort St. George Legislative Seat, Chennai",
        "latitude": 13.0795,
        "longitude": 80.2878,
        "image_url": "/assets/history/tamil-nadu-renaming.jpg",
        "image_caption": "Fort St. George Legislative Seat and official seal of Tamil Nadu",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1445) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1445",
        "license": "CC BY-SA 4.0",
        "tags": "history,tamilnadu,modern,annadurai,statehood",
        "related_slugs": "classical-language-declaration,bharati-nationalist-poetry",
    },
    {
        "slug": "classical-language-declaration",
        "content_type": "history",
        "title_ta": "தமிழ் மொழிக்குச் செம்மொழித் தகுதி வழங்கப்படுதல்",
        "title_en": "Declaration of Tamil as First Classical Language of India",
        "category": "History",
        "summary_ta": "2004-இல் இந்திய அரசினால் தமிழ் மொழி இந்தியாவின் முதல் செம்மொழியாக அதிகாரப்பூர்வமாக அறிவிக்கப்பட்டது.",
        "summary_en": "In 2004, the Government of India formally accords Tamil the status of India's first official Classical Language.",
        "content_ta": "தமிழ் மொழியின் தொன்மை, தனித்தன்மை, செவ்வியல் இலக்கிய வளம் மற்றும் தொடர்ச்சி ஆகியவற்றைக் கருத்தில் கொண்டு 2004-ஆம் ஆண்டு அக்டோபர் 12 அன்று இந்திய அரசால் தமிழ் மொழிக்கு 'செம்மொழி' (Classical Language) தகுதி வழங்கப்பட்டது. இந்தியாவில் இத்தகுதியைப் பெற்ற முதல் மொழி தமிழாகும். இதனைத் தொடர்ந்து சென்னையில் மத்திய செம்மொழித் தமிழாய்வு நிறுவனம் (CICT) நிறுவப்பட்டது.",
        "content_en": "On October 12, 2004, the Government of India formally recognized Tamil as the country's first official Classical Language (Semmozhi), acknowledging its ancient antiquity, literary independence, and unbroken cultural tradition spanning over two millennia. This led to the establishment of the Central Institute of Classical Tamil (CICT) in Chennai.",
        "date_order": 2004,
        "date_label": "October 12, 2004 CE",
        "era": "Modern Era",
        "region": "Chennai, India",
        "period": "Contemporary Era",
        "location_name": "Central Institute of Classical Tamil, Chennai",
        "latitude": 13.0067,
        "longitude": 80.2570,
        "image_url": "/assets/history/classical-tamil-semmozhi.jpg",
        "image_caption": "Classical Tamil research and Semmozhi preservation emblem",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q5885) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q5885",
        "license": "CC BY-SA 4.0",
        "tags": "history,classical,language,semmozhi,2004",
        "related_slugs": "reorganization-tamil-nadu,thirukkural-composition",
    },
]
