"""
Seed dataset for Feature 6 — Tamil Knowledge Library.
Provides structured, source-attributed reference articles on Tamil language, grammar,
architecture, manuscripts, archaeology, traditions, and global heritage.
Uses content_type = "article".
"""

SEED_KNOWLEDGE_ITEMS = [
    {
        "slug": "tamil-language-origins",
        "content_type": "article",
        "title_ta": "தமிழ் மொழியின் தொன்மையும் திராவிட மொழிக் குடும்பமும்",
        "title_en": "Origins and Antiquity of the Tamil Language",
        "category": "Language",
        "summary_ta": "உலகில் இன்றளவும் உயிர்ப்புடன் இருக்கும் மிகத்தொன்மையான செம்மொழிகளுள் ஒன்றான தமிழின் தோற்றமும் அதன் சிறப்புகளும்.",
        "summary_en": "An exploration of Tamil as one of the world's longest-surviving classical languages and the core of the Dravidian linguistic family.",
        "content_ta": "தமிழ் மொழி திராவிட மொழிக் குடும்பத்தின் முதன்மை மொழியாகும். இது உலகில் இன்றளவும் உயிர்ப்புடன் இருக்கும் மிகத்தொன்மையான செம்மொழிகளுள் ஒன்றாகவும், இரண்டாயிரத்து ஐந்நூறு ஆண்டுகளுக்கும் மேலான தொடர்ச்சியான இலக்கிய மரபைக் கொண்டதாகவும் திகழ்கிறது. வரலாற்றுக்கு முந்தைய தொல்பழங்காலம் முதல் தற்காலம் வரை உலகளாவிய அளவிலும், குறிப்பாகப் பண்டைய தமிழகப் பகுதிகளிலும் இதன் வரலாறு மிக ஆழமாக வேரூன்றிப் பரவியுள்ளது.\n\nதமிழகத்தில் நடைபெற்ற பல்வேறு தொல்பொருள் அகழ்வாராய்ச்சிகள் மற்றும் மாங்குளம், கொடுமணல், கீழடி போன்ற இடங்களில் கிடைக்கப்பெற்ற தமிழி (தமிழ் பிராமி) பானை ஓடுகள் மற்றும் குகைக் கல்வெட்டுகள் மூலம் தமிழ் மொழியின் எழுத்து வடிவம் கி.மு. 6-ஆம் நூற்றாண்டுக்கும் முற்பட்டது என்பது அறிவியல்பூர்வமாக உறுதிசெய்யப்பட்டுள்ளது. இதன் சிறப்பை உணர்ந்து 2004-ஆம் ஆண்டில், இந்தியாவில் முதன்முதலில் 'செம்மொழி' (Classical Language) தகுதி பெற்ற மொழி தமிழாகும். நிகரற்ற சொல்வளம், தனித்துவமான இலக்கணச் செறிவு மற்றும் கால மாற்றங்களைத் தாங்கி நிற்கும் நெகிழ்வுத்தன்மை ஆகியவை மொழியியல் வரலாற்றில் தமிழின் அழியாத சிறப்பம்சங்களாகும்.",
        "content_en": "Tamil belongs to the South Dravidian branch of languages and boasts an unbroken, rich literary tradition spanning well over 2,500 years, firmly establishing it as one of the world's longest-surviving classical languages. Investigated thoroughly by the Ezhuthaani Editorial & Epigraphy Research Team, its complex linguistic history traces an extraordinary evolution from prehistoric origins to contemporary global usage, while maintaining its deep ancestral roots within Ancient Tamilakam.\n\nRemarkable epigraphic discoveries, particularly the ancient Tamil-Brahmi scripts found inscribed on cave walls and terracotta pottery at archaeological sites like Mangulam, Kodumanal, and Keezhadi, definitively date written Tamil to at least the 6th century BCE. Recognizing its profound historical and cultural significance, the Government of India officially declared Tamil as its first Classical Language in 2004. Its unique agglutinative structure, reliance on pure ancient roots, and continuous, vibrant usage make it a living linguistic treasure that remains central to the Dravidian linguistic family.",
        "author": "Ezhuthaani Editorial & Epigraphy Research Team",
        "period": "Prehistoric – Present",
        "era": "Classical & Contemporary",
        "genre": "Linguistic History",
        "literary_tradition": "Language & Philology",
        "region": "Global / Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Tamil_language",
        "image_url": "/assets/library/kaveri_delta.jpg",
        "image_caption": "Mangulam Tamil-Brahmi inscription dating back to the 3rd century BCE",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q9129) & Archaeological Survey of India",
        "source_url": "https://www.wikidata.org/wiki/Q9129",
        "license": "CC BY-SA 4.0",
        "tags": "language,linguistics,classical,dravidian,antiquity,epigraphy",
        "related_slugs": "tolkappiyam-grammatical-tradition,sangam-literature-anthologies,keezhadi-excavations-civilization",
    },
    {
        "slug": "tolkappiyam-grammatical-tradition",
        "content_type": "article",
        "title_ta": "தொல்காப்பியம்: தமிழ் இலக்கண மற்றும் வாழ்வியல் மரபு",
        "title_en": "Tolkappiyam: Grammatical Rigor and Poetics of Life",
        "category": "Grammar",
        "summary_ta": "எழுத்து, சொல் மற்றும் பொருள் (வாழ்வியல்) ஆகிய மூன்றிற்கும் விரிவான விதிகளை வகுத்த தமிழ் மொழியின் பழமையான இலக்கண நூல்.",
        "summary_en": "The oldest surviving Tamil grammatical masterpiece that codified phonology, syntax, and human poetic experience (Porul).",
        "content_ta": "தொல்காப்பியம் என்பது கி.மு. 500 முதல் 300 வரையிலான முற்சங்க மற்றும் சங்க காலக் கட்டத்தில் பண்டைய தமிழகத்தில் தொல்காப்பியரால் மிகச் சிறப்பாக இயற்றப்பட்ட தலைசிறந்த நூலாகும். இது இன்றுவரை நமக்குக் கிடைத்துள்ள தமிழ் மொழியின் மிகப்பழமையான இலக்கண நூலாகத் திகழ்கிறது. இந்நூல் எழுத்து, சொல் மற்றும் பொருள் (வாழ்வியல்) ஆகிய மூன்று முக்கியப் பிரிவுகளுக்கும் மிக விரிவான மற்றும் நுட்பமான விதிகளை வகுத்துள்ளது.\n\nஇது எழுத்ததிகாரம், சொல்லதிகாரம், பொருளதிகாரம் எனும் மூன்று பெரும் அதிகாரங்களைக் கொண்டுள்ளது. வடமொழி மற்றும் பிற மொழி இலக்கணங்களைப் போலன்றி, தொல்காப்பியம் வெறுமனே மொழிக்கான இலக்கணத்தை மட்டும் வரையறுக்காமல், மக்களின் அகம் (காதல்), புறம் (வீரம்) சார்ந்த வாழ்வியலுக்கான (பொருளதிகாரம்) இலக்கணத்தையும் சேர்த்தே வகுத்துள்ளது. இது உலகில் வேறு எந்த மொழியிலும் காணக் கிடைக்காத தமிழின் தனித்துவமான சிறப்பாகும்.",
        "content_en": "Composed by the esteemed scholar Tolkappiyar between c. 500 BCE and 300 BCE in Ancient Tamilakam, the Tolkappiyam stands proudly as the oldest surviving Tamil grammatical masterpiece. This monumental Pre-Sangam and Sangam era treatise is systematically divided into three major sections: Ezhuthu (focusing on Phonology and Graphemic rules), Sol (detailing Etymology and Syntax), and Porul (exploring Socio-poetic conventions).\n\nWhile the first two sections, Ezhuthu and Sol, rigorously govern the structural mechanics of speech and script, the third section, Porul, uniquely sets this work apart from global grammatical texts. Porul intricately codifies the human poetic experience, exploring deeply into human emotion, geographical landscapes, warfare protocols, ethics, and societal organization. Analyzed extensively by Ezhuthaani Scholars, this foundational text originally established the 30 primary letters and 12 dependent letter categories that define classical Tamil.",
        "author": "Tolkappiyar (Analyzed by Ezhuthaani Scholars)",
        "period": "c. 500 BCE – 300 BCE",
        "era": "Pre-Sangam / Sangam",
        "genre": "Grammatical Treatise",
        "literary_tradition": "Grammar & Aesthetics",
        "region": "Ancient Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pdf/pm0073.pdf",
        "image_url": "/assets/library/tholkappiyam_leaf.jpg",
        "image_caption": "Palm-leaf manuscript copy of Tolkappiyam commentary",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q2002773) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q2002773",
        "license": "Public Domain / CC0",
        "tags": "grammar,tolkappiyam,ezhuthu,sol,porul,linguistics,rules",
        "related_slugs": "tamil-language-origins,sangam-literature-anthologies",
    },
    {
        "slug": "dravidian-temple-architecture",
        "content_type": "article",
        "title_ta": "திராவிடக் கோயில் கட்டிடக்கலை மற்றும் சிற்பக்கலை பொறியியல்",
        "title_en": "Dravidian Temple Architecture and Structural Engineering",
        "category": "Architecture",
        "summary_ta": "பல்லவர், சோழர், பாண்டியர் மற்றும் நாயக்கர் காலத்தில் உருவான விமானம், கோபுரம் மற்றும் ஆயிரம் கால் மண்டபங்களின் கலைநுட்பம்.",
        "summary_en": "The evolution of stone temples from rock-cut monoliths to soaring gopurams and acoustic stone pillars.",
        "content_ta": "திராவிடக் கோயில் கட்டிடக்கலை என்பது கி.பி. 6 முதல் 17 ஆம் நூற்றாண்டு வரையிலான இடைக்காலத் தமிழகத்தில் தோன்றி வளர்ந்த ஒரு மாபெரும் கலை வடிவமாகும். பல்லவர், சோழர், பாண்டியர் மற்றும் நாயக்கர் ஆகிய மாமன்னர்களின் ஆட்சிக் காலத்தில் உருவான இந்தக் கட்டிடக்கலை மற்றும் சிற்பக்கலை பொறியியல் உலக அளவில் புகழ்பெற்றதாகும். இது மாமல்லபுரத்தில் உள்ள பல்லவர்களின் குடைவரைச் கோயில்கள் மற்றும் ஒற்றைக்கல் ரதங்களில் தொடங்கி, சோழர்களின் வானளாவிய மாபெரும் கற்றளிகள் (தஞ்சைப் பெரிய கோயில்) வழியாகத் தொடர்ந்தது.\n\nகாலப்போக்கில் இக்கலை நுட்பம் மேலும் வளர்ச்சியடைந்து, பாண்டியர்கள் மற்றும் நாயக்கர்களின் ஆட்சியில் வண்ணமயமான, மிக உயரமான கோபுரங்கள் மற்றும் நுணுக்கமான வேலைப்பாடுகள் கொண்ட ஆயிரம் கால் மண்டபங்களாக முழுமை பெற்றது. ஆகம விதிகள், வாஸ்து சாஸ்திரம் மற்றும் மிகத் துல்லியமான இயற்பியல் எடைக் கணிப்புகளை அடிப்படையாகக் கொண்டு, எவ்வித சுண்ணக்கலவையுமின்றி முழுக்க முழுக்கக் கற்களை மட்டுமே ஒன்றோடொன்று பிணைத்துக் கட்டப்பட்ட இக்கோயில்கள், தென்னிந்தியத் தமிழர்களின் அளப்பரிய பொறியியல் சாதனைக்குச் சிறந்த சான்றாகும்.",
        "content_en": "Documented as a profoundly major segment of global architectural history, Dravidian architecture developed in highly distinct and majestic historical phases across Tamil Nadu and South India from the 6th to the 17th Century CE. During this vibrant Medieval Tamilakam era, the evolution of stone temples progressed magnificently from the early rock-cut monoliths and cave temples pioneered under the Pallavas (6th–8th centuries) to the breathtakingly soaring Vimana pyramid structures perfected under the Imperial Cholas, best exemplified by the 11th-century Tanjavur Brihadisvara Temple.\n\nThis architectural style eventually culminated in the construction of massive, multi-tiered Gopuram gateways adorned with thousands of intricate stucco sculptures under the later Pandyas and Nayaks. The notable features of this advanced structural engineering include flawless interlocking granite masonry achieved entirely without the use of mortar, scientifically carved acoustic musical stone pillars, and expansive, awe-inspiring thousand-pillar halls (Aayiram Kaal Mandapam) that showcase unparalleled artisan skill.",
        "author": "Architectural History Desk",
        "period": "6th Century – 17th Century CE",
        "era": "Medieval Tamilakam",
        "genre": "Architectural History",
        "literary_tradition": "Vastu & Aesthetics",
        "region": "Tamil Nadu & South India",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Dravidian_architecture",
        "image_url": "/assets/library/madurai_meenakshi.jpg",
        "image_caption": "The 216-foot granite Vimana of Tanjavur Brihadisvara Temple built by Raja Raja Chola I",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1256334) & Archaeological Survey of India",
        "source_url": "https://www.wikidata.org/wiki/Q1256334",
        "license": "CC BY-SA 4.0",
        "tags": "architecture,temples,chola,pallava,tanjavur,engineering,granite",
        "related_slugs": "great-living-chola-temples,chola-lost-wax-bronze-casting,ponniyin-selvan-epic-novel",
    },
    {
        "slug": "keezhadi-excavations-civilization",
        "content_type": "article",
        "title_ta": "கீழடி அகழ்வாராய்ச்சி: வைகைக்கரை நகரச் சங்க நாகரிகம்",
        "title_en": "Keezhadi Excavations: Sangam Age Urban Civilization on the Vaigai",
        "category": "History",
        "summary_ta": "சிவங்கை மாவட்டம் கீழடியில் கண்டெடுக்கப்பட்ட கி.மு. 6-ஆம் நூற்றாண்டு நகர நாகரிகச் சான்றுகளும் தமிழ் பிராமி பானை ஓடுகளும்.",
        "summary_en": "Scientific archaeological evidence proving an educated, literate urban Sangam civilization along the Vaigai River.",
        "content_ta": "மதுரைக்கு அருகாமையில் சிவங்கை மாவட்டம் வைகை நதிக்கரையில் அமைந்துள்ள கீழடியில், தமிழ்நாடு அரசு தொல்லியல் துறை நடத்திய விரிவான அகழ்வாராய்ச்சிகள் ஒட்டுமொத்தத் தமிழ் வரலாற்றிலும் ஒரு பெரும் திருப்புமுனையை ஏற்படுத்தியுள்ளன. கி.மு. 600 முதல் கி.பி. 300 வரையிலான சங்க காலத்தைச் சேர்ந்த இந்த நிலப்பரப்பில் மேற்கொள்ளப்பட்ட ஆய்வுகளில், கி.மு. 580 காலத்தைச் சேர்ந்த செங்கற்களால் ஆன மேம்பட்ட பாதாள வடிகால் அமைப்புகள், உறை கிணறுகள் மற்றும் விரிவான கட்டிட இடிபாடுகள் கண்டுபிடிக்கப்பட்டுள்ளன.\n\nமேலும், நெசவுத் தொழில் உபகரணங்கள், தந்தத்திலான பகடைகள், சுடுமண் பொம்மைகள் மற்றும் பல்வேறு தங்க அணிகலன்களும் இங்கு ஏராளமாகக் கண்டெடுக்கப்பட்டுள்ளன. எல்லாவற்றிற்கும் மேலாக, ஆதன், குவிரன், எவ்வி போன்ற தமிழ்ப் பெயர்கள் பொறிக்கப்பட்ட 56-க்கும் மேற்பட்ட தமிழ் பிராமி பானை ஓடுகள் கண்டெடுக்கப்பட்டதன் மூலம், சங்க காலத்தில் எழுத்தறிவு பெற்ற ஒரு மிகச் சிறந்த, பன்முகத்தன்மை கொண்ட நகர நாகரிகம் இங்கு வாழ்ந்ததை இந்த ஆய்வுகள் அறிவியல்பூர்வமாக நிரூபித்துள்ளன.",
        "content_en": "Groundbreaking excavations conducted at Keezhadi in the Vaigai Valley, Sivagangai, led by the Tamil Nadu State Department of Archaeology, have yielded definitive AMS carbon-dating evidence that successfully pushes the timeline of the Sangam era back to at least 580 BCE (spanning roughly c. 600 BCE – 300 CE). This comprehensive archaeological report provides undeniable scientific evidence proving the existence of an educated, highly literate, and industrially advanced urban Sangam civilization thriving securely along the banks of the Vaigai River.\n\nThe diverse range of discovered artifacts includes sophisticated terracotta ring wells, structured brick drainage networks indicating advanced town planning, intricately carved ivory dice, terracotta figurines, and precious quartz beads. Crucially, the excavation uncovered over 56 potsherds inscribed with clear Tamil-Brahmi script featuring ancient personal names like Aadhan, Kungan, and Evvi. This extraordinary epigraphical find confirms that literacy was not restricted to the elite, but was widespread among common citizens in Sangam-era urban settlements.",
        "author": "Archeology & Heritage Desk",
        "period": "c. 600 BCE – 300 CE",
        "era": "Sangam Era Archaeology",
        "genre": "Archaeological Report",
        "literary_tradition": "Historiography",
        "region": "Vaigai Valley, Sivagangai",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Keezhadi_excavations",
        "image_url": "/assets/library/thirumukkudal_hospital.jpg",
        "image_caption": "Tamil-Brahmi potsherds unearthed during Keezhadi excavations",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q28174068) & Tamil Nadu State Department of Archaeology",
        "source_url": "https://www.wikidata.org/wiki/Q28174068",
        "license": "CC BY-SA 4.0",
        "tags": "keezhadi,archaeology,sangam,vaigai,history,epigraphy,urbanism",
        "related_slugs": "sangam-assembly-foundations,sangam-literature-anthologies,tamil-language-origins",
    },
    {
        "slug": "palm-leaf-manuscripts-preservation",
        "content_type": "article",
        "title_ta": "பனைஓலைச் சுவடிகள்: தமிழ் அறிவின் பாதுகாப்பு மரபு",
        "title_en": "Preservation of Ancient Tamil Palm-Leaf Manuscripts (Oolai Chuvadi)",
        "category": "Traditions",
        "summary_ta": "எழுத்தாணி கொண்டு பனைஓலைகளில் தமிழ் இலக்கியம், மருத்துவம், வானியல் ஆகியவற்றை பொறித்து பாதுகாத்த பண்டைய தொழில்நுட்பம்.",
        "summary_en": "The traditional technology of preserving Tamil literature, Siddha medicine, and astronomy using iron styluses on cured palm leaves.",
        "content_ta": "பண்டைய காலம் முதல் 19-ஆம் நூற்றாண்டு வரையிலான நீண்ட காலகட்டத்தில், தமிழகத்தில் நவீன அச்சு எந்திரங்கள் அறிமுகமாவதற்கு முன்பு, தமிழர்களின் ஒட்டுமொத்த அறிவுக் களஞ்சியங்களும் 'ஓலைச்சுவடி'களிலேயே மிகவும் கவனமாகப் பாதுகாக்கப்பட்டன. இயற்கை வளமான பனை ஓலைகளை வெட்டி, நீரில் கொதிக்கவைத்து, நிழலில் உலர்த்திப் பதப்படுத்தி சுவடிகளாக மாற்றும் இம்முறை ஒரு சிறந்த பாரம்பரியத் தொழில்நுட்பமாகும். பதப்படுத்தப்பட்ட இந்த ஓலைகளில் 'எழுத்தாணி' (Iron Stylus) எனும் கூர்மையான இரும்பு ஊசியைக் கொண்டு சங்க காலத் தமிழ் இலக்கியம், சித்த மருத்துவம், மற்றும் வானியல் சார்ந்த அரிய தகவல்கள் ஆழமாகப் பொறிக்கப்பட்டு எழுதப்பட்டன.\n\nஓலையில் பொறிக்கப்பட்ட எழுத்துக்கள் காலப்போக்கில் தெளிவாகத் தெரிவதற்காகவும், பூச்சிகள் அரிக்காமல் இருப்பதற்காகவும் சுவடியின் மீது மஞ்சள், நல்லெண்ணெய் மற்றும் மூலிகைக் கரி பொடி கலந்த கலவை பூசப்பட்டது. அழிந்துபோகும் நிலையிலிருந்த இந்த ஓலைச்சுவடிகளை, தமிழ்த்தாத்தா உ.வே. சாமிநாதையர் போன்ற மாபெரும் தமிழறிஞர்கள் தங்கள் வாழ்நாளெல்லாம் கிராமங்கள் தோறும் மாட்டு வண்டியில் சென்று சேகரித்துப் பதிப்பித்திராவிட்டால், இன்று நாம் காணும் ஒப்பற்ற சங்க இலக்கியங்கள் பலவும் நமக்கு என்றென்றைக்குமாகக் கிடைக்காமலேயே போயிருக்கும்.",
        "content_en": "Long before the advent of modern printing presses, the traditional and highly sophisticated technology for preserving ancient Tamil literature, complex medical (Siddha) knowledge, astronomical charts, and legal texts involved the extensive use of cured Asian Palmyra palm leaves (Borassus flabellifer). Originating in Ancient Tamilakam and heavily utilized continuously from prehistoric times until the late 19th Century CE during the Pre-Modern era, this textual archiving method was the backbone of knowledge transfer. Dedicated scribes painstakingly used a specialized, sharpened iron stylus (known as an Ezhuthaani) to carefully incise tiny, precise characters directly onto leaves that had been previously dried, boiled, and smoothed.\n\nTo significantly heighten the readability of the etched text and naturally protect the organic material from destructive insects and decay, a special protective paste made of lampblack, turmeric, and aromatic herbal oils was gently rubbed over the manuscript's surface. Visionary scholars and early philologists, most notably U. V. Swaminatha Iyer, spent decades relentlessly traveling across remote villages, physically retrieving, painstakingly decoding, and finally publishing these priceless textual archives for the modern world.",
        "author": "Manuscripts Research Group",
        "period": "Ancient – 19th Century CE",
        "era": "Pre-Modern",
        "genre": "Cultural Technology",
        "literary_tradition": "Textual Archiving",
        "region": "Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Palm-leaf_manuscript",
        "image_url": "/assets/library/sangam_weaving.jpg",
        "image_caption": "Traditional palm-leaf manuscript bound with cotton thread and wooden protective covers",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1526438) & U.V. Swaminatha Iyer Library",
        "source_url": "https://www.wikidata.org/wiki/Q1526438",
        "license": "CC BY 3.0",
        "tags": "manuscripts,oolai_chuvadi,ezhuthaani,preservation,siddha,swaminatha_iyer",
        "related_slugs": "tolkappiyam-grammatical-tradition,sangam-literature-anthologies",
    },
    {
        "slug": "chola-lost-wax-bronze-casting",
        "content_type": "article",
        "title_ta": "சோழர் கால மெழுகு வார்ப்பு வெண்கலச் சிலைகள்",
        "title_en": "Chola Lost-Wax Bronze Metallurgy and Sculptural Perfection",
        "category": "Culture",
        "summary_ta": "மதுச்சிக்ட்ட விதானம் (Cire Perdue) முறையில் சோழ கைவினைஞர்களால் வார்க்கப்பட்ட உலகப் புகழ்பெற்ற நடராஜர் மற்றும் தெய்வச் சிலைகள்.",
        "summary_en": "The mastery of lost-wax investment casting that produced iconic Nataraja icons admired globally for rhythm and proportion.",
        "content_ta": "சோழப் பேரரசு செழித்தோங்கிய கி.பி. 9 முதல் 13 ஆம் நூற்றாண்டு வரையிலான காலகட்டத்தில், தஞ்சாவூர் மற்றும் சுவாமிமலைப் பகுதிகளில் தமிழர்களின் உலோகச் சிற்பக்கலையானது அதன் ஈடு இணையற்ற வரலாற்று உச்சத்தை எட்டியது. இப்பகுதிகளில் வாழ்ந்த கைவினைஞர்கள் மற்றும் ஸ்தபதிகள் 'மதுச்சிஷ்ட விதானம்' (Lost-Wax Process / Cire Perdue) எனப்படும் மிகக் கடினமான பாரம்பரிய உலோக வார்ப்பு முறையில் பல்வேறு தெய்வச் சிலைகளை உருவாக்கினர். முதலில் தேன்மெழுகால் தத்ரூபமான உருவம் செய்து, அதன் மீது ஆற்றுக்களிமண் பூசி உலரவைப்பர். பின்னர் சுடவைத்து மெழுகை உருக்கி வெளியேற்றிவிட்டு, அந்த அச்சுக்குள் செம்பு, பித்தளை, துத்தநாகம், தங்கம், வெள்ளி கலந்த ஐம்பொன் (வெண்கலம்) உலோகத்தை ஊற்றி இச்சிலைகள் வார்க்கப்பட்டன.\n\nஇம்முறையில் வடிக்கப்பட்ட ஆனந்த தாண்டவ நடராஜர் சிலைகள் மற்றும் பிற தெய்வச் சிலைகள், உலகச் சிற்பக் கலையின் தலைசிறந்த படைப்புகளாக இன்றுவரை பல நாடுகளின் அருங்காட்சியகங்களில் கொண்டாடப்படுகின்றன. குறிப்பாக, நடராஜர் சிலை என்பது வெறுமனே ஒரு கலைப்படைப்பு மட்டுமல்லாமல், படைத்தல், காத்தல், அழித்தல் ஆகிய பிரபஞ்ச சுழற்சியை உணர்த்தும் தத்துவார்த்த ரீதியாகவும், மிகத் துல்லியமான இயற்பியல் சமநிலை ரீதியாகவும் வடிக்கப்பட்ட ஒரு மாபெரும் அறிவியல் மற்றும் ஆன்மீகப் படைப்பாகும்.",
        "content_en": "The majestic Imperial Chola bronzes, crafted predominantly between the 9th and 13th centuries CE, unequivocally represent an absolute pinnacle of metal casting and sculptural perfection in the history of world art. Centered around the culturally rich regions of Thanjavur and Swamimalai during the zenith of the Chola Era, highly skilled local artisans known as Sthapathis utilized the ancient and complex lost-wax investment casting method (Cire Perdue or Madhuchishtavidhanam). The process required them to sculpt meticulous, highly detailed wax models, completely coat them in specialized river clay, bake the mold to melt out the wax, and finally pour molten Panchaloha—a sacred five-metal alloy consisting of copper, brass, zinc, gold, and silver—into the cavity.\n\nThe unparalleled mastery of this labor-intensive technique produced the world-famous, iconic Nataraja (Cosmic Dancer) icons, which continue to be admired globally by art historians for their flawless rhythm, anatomical proportion, and dynamic fluidity. Far beyond mere aesthetic beauty, the Nataraja embodies profound cosmic principles, seamlessly integrating creation, preservation, destruction, illusion, and salvation into one breathtakingly fluid and mathematically balanced dynamic equilibrium.",
        "author": "Arts & Metallurgy Heritage Team",
        "period": "9th – 13th Century CE",
        "era": "Chola Era",
        "genre": "Art History",
        "literary_tradition": "Iconography & Craft",
        "region": "Thanjavur & Swamimalai",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Chola_bronzes",
        "image_url": "/assets/library/bronze_casting.jpg",
        "image_caption": "Chola Chidambaram Nataraja cosmic dancer icon cast in bronze",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q2926154) & Victoria and Albert Museum",
        "source_url": "https://www.wikidata.org/wiki/Q2926154",
        "license": "CC BY-SA 4.0",
        "tags": "chola,bronze,nataraja,swamimalai,sculpture,metallurgy,art",
        "related_slugs": "great-living-chola-temples,dravidian-temple-architecture,ponniyin-selvan-epic-novel",
    },
    {
        "slug": "hero-stones-nadukal-tradition",
        "content_type": "article",
        "title_ta": "நடுகல் (வீரக்கல்) வழிபாடு: சங்க கால நினைவுச் சின்ன மரபு",
        "title_en": "Hero Stones (Nadukal): Commemorative Traditions of Ancient Warriors",
        "category": "Traditions",
        "summary_ta": "நாட்டையும் மக்களையும் கால்நடைகளையும் காப்பாற்ற உயிர்த்தியாகம் செய்த வீரர்களுக்கு எழுப்பப்பட்ட சங்க கால நடுகற்கள்.",
        "summary_en": "Ancient stone memorials carved with images and inscriptions honoring martyrs who gave their lives in cattle raids and border defenses.",
        "content_ta": "பழங்கால இரும்பு யுகம் முதல் இடைக்காலம் வரை (சராசரியாக கி.மு. 500 முதல் கி.பி. 1500 வரை) தர்மபுரி, திருவண்ணாமலை மற்றும் செங்கம் உள்ளிட்ட தமிழகத்தின் பல பகுதிகளில் நடுகல் (வீரக்கல்) நடும் வழக்கம் பரவலாக இருந்துள்ளது. சங்க இலக்கியங்களில் 'நடுகல் வழிபாடு' என்பது புறத்திணை மரபாக மிக முக்கிய இடத்தைப் பிடித்துள்ளது. அந்நியப் படையெடுப்பிலிருந்து நாட்டை மற்றும் தன் ஊரைக் காத்தல், எதிரிகள் கவர்ந்து சென்ற ஆனிரைகளை (கால்நடைகள்) மீட்டு வருதல், மற்றும் கொடிய விலங்குகளுடன் போராடி மக்களின் உயிரைக் காத்தல் போன்ற வீரச் செயல்களில் ஈடுபட்டுப் போர்க்களத்தில் வீரமரணம் அடைந்த தியாகிகளின் நினைவாக இந்த நடுகற்கள் அமைக்கப்பட்டன.\n\nவீரர்களின் உருவம் பொறிக்கப்பட்டு, அவர்களின் பெயர், புகழ் மற்றும் வீரச் சாதனைகளை எழுத்துக்களால் செதுக்கி இவை எழுப்பப்பட்டன. தொல்காப்பியம் இந்நடுகற்களை நிறுவுவதற்கான ஆறு படிநிலைகளை மிகத் தெளிவாக வரையறுத்துள்ளது. மயிலாடும்பாறை மற்றும் செங்கம் போன்ற இடங்களில் அகழ்வாராய்ச்சியின் போது கண்டெடுக்கப்பட்ட நூற்றுக்கணக்கான நடுகற்கள், பண்டைத் தமிழர்களின் ஈடு இணையற்ற வீர மரபையும், நாட்டுக்காக உயிர்த்தியாகம் செய்த முன்னோர்களைக் கடவுளாக வழிபடும் உன்னத முறையையும் இன்றும் நமக்குத் தெளிவாக உணர்த்துகின்றன.",
        "content_en": "Nadukal (commonly referred to as Hero Stones) are highly significant memorial stones widely erected across regions like Dharmapuri and Chengam in Tamil Nadu, dating from the early Iron Age (c. 500 BCE) entirely through the medieval period up to 1500 CE. Standing as a testament to the region's martial history, these ancient commemorative stone memorials were beautifully carved with bas-relief images and detailed inscriptions. They were specifically created to honor courageous martyrs who selflessly gave their lives actively defending their localized villages, bravely rescuing stolen cattle during raids (a prominent practice known as Aanirai Kavaruthal/Meettal), or fighting ferocious wild beasts to protect their community.\n\nThe process of erecting a hero stone was not arbitrary but followed a deeply codified set of six sacred rituals detailed explicitly in the ancient grammatical text, Tolkappiyam. These solemn steps included Gatchi (locating the perfect stone), Kol-thal (cutting it appropriately), Neeruppatu (ritual purification in water), Nadukal (the physical erection of the stone), Perumpadai (formal consecration with offerings), and Vazhthu (singing verses of praise). Today, these stones serve as crucial ethno-historical markers linking modern generations to ancient Sangam martial traditions.",
        "author": "Epigraphy & Folklore Desk",
        "period": "c. 500 BCE – 1500 CE",
        "era": "Ancient & Medieval",
        "genre": "Ethno-History",
        "literary_tradition": "Puram Tradition",
        "region": "Dharmapuri, Chengam, Tamil Nadu",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Hero_stone",
        "image_url": "/assets/library/siddha_medicine.jpg",
        "image_caption": "Inscribed Tamil hero stone with warrior figures and weaponry relief",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534591) & Tamil Nadu Epigraphy Department",
        "source_url": "https://www.wikidata.org/wiki/Q3534591",
        "license": "CC BY-SA 4.0",
        "tags": "nadukal,hero_stone,warriors,sangam,epigraphy,chengam,puram",
        "related_slugs": "sangam-literature-anthologies,keezhadi-excavations-civilization,tolkappiyam-grammatical-tradition",
    },
    {
        "slug": "global-tamil-diaspora-history",
        "content_type": "article",
        "title_ta": "உலகத் தமிழ் புலம்பெயர் வரலாறும் கடல்வழி வணிகமும்",
        "title_en": "Global Tamil Diaspora and Maritime Trade Heritage",
        "category": "Regional Practices",
        "summary_ta": "தென்கிழக்காசியா, இலங்கை, ரீயூனியன், மொரீஷியஸ் மற்றும் மேலைநாடுகளில் தமிழர்களின் வரலாற்றுச் சுவடுகளும் வணிகத் தொடர்புகளும்.",
        "summary_en": "The history of Tamil seafaring merchant guilds (Manigramam, Ayyavole) and modern global migration across 80+ countries.",
        "content_ta": "தமிழர்களின் கடல்வழி வணிகம் மற்றும் உலகளாவிய புலம்பெயர் வரலாறு என்பது கி.பி. முதல் நூற்றாண்டு முதல் தற்காலம் வரை தொடர்ந்து விரிவடைந்து வரும் ஒரு நெடிய சமூகவியல் வரலாறாகும். இயற்கையிலேயே தமிழர்கள் பண்டைய காலத்திலிருந்தே சிறந்த கப்பல் கட்டும் திறன் கொண்ட மாலுமிகளாகவும், துணிச்சலான வணிகர்களாகவும் திகழ்ந்தனர். இடைக்காலத்தில் மணிகிராமம், அய்யாவொழில் ஐந்நூற்றுவர் மற்றும் அஞ்சுவண்ணம் போன்ற மாபெரும் தமிழ் வணிகக் குழுக்கள் உருவாகின. இவர்கள் ரோம், கிரீஸ், எகிப்து, அலெக்ஸாண்டிரியா தொடங்கி கிழக்கு ஆசியாவில் உள்ள சீனா (குவாங்சோ) மற்றும் சுமத்ரா வரை தங்கள் கடல்வழி வணிக எல்லையை மிக வெற்றிகரமாக விரிவுபடுத்தினர்.\n\nஇதன் தொடர்ச்சியாக, நவீன காலகட்டமான 19 மற்றும் 20-ஆம் நூற்றாண்டுகளில், பல்வேறு பொருளாதாரக் காரணங்களுக்காகப் பல தமிழர்கள் ஒப்பந்தத் தொழிலாளர்களாகவும், அதிகாரிகளாகவும், குடியேறிகளாகவும் கடல் கடந்து பயணம் மேற்கொண்டனர். மொரீஷியஸ், ரீயூனியன், மலேசியா, சிங்கப்பூர், இலங்கை, தென்னாப்பிரிக்கா, பிஜி போன்ற நாடுகளுக்கும், பின்னர் கனடா உள்ளிட்ட 80க்கும் மேற்பட்ட மேலைநாடுகளுக்கும் சென்ற தமிழர்கள் அங்கே நிரந்தரமாகக் குடியேறினர். இன்று உலகம் முழுவதும் வாழும் கோடிக்கணக்கான தமிழர்கள், இத்தனை நூற்றாண்டுகள் கடந்தும் தங்களின் தாய்மொழி, உயர்ந்த பண்பாடு, மற்றும் பாரம்பரியத் திருவிழாக்களை மிகுந்த உறுதியுடனும் பெருமையுடனும் பாதுகாத்து வருகின்றனர்.",
        "content_en": "Exploring a vast sociological history stretching from the 1st Century CE to the present day, the global Tamil diaspora and its associated maritime trade heritage span dynamically across Southeast Asia, the vast Indian Ocean, and over 80 countries worldwide. Tamil maritime history alone spans two millennia, originally driven by powerful, highly organized medieval seafaring merchant guilds such as the Manigramam, the Ayyavole 500, and the Anjuvannam. These formidable merchant fleets successfully operated and controlled lucrative trading ports extending all the way from Guangzhou in China to Alexandria in Egypt, firmly establishing Tamilakam as an ancient global economic powerhouse.\n\nIn the modern era, particularly during the turbulent 19th and 20th centuries, large successive waves of indentured laborers, professionals, and various emigrants carried their rich Tamil cultural heritage across oceans. They established strong, enduring communities in distant lands including Malaysia, Singapore, Sri Lanka, Mauritius, Réunion, Fiji, South Africa, and later, Canada and Europe. Today, an estimated 85+ million Tamil speakers form an incredibly vibrant, highly resilient global diaspora that continues to actively celebrate and preserve its ancient linguistic and cultural traditions.",
        "author": "Global Diaspora Studies Desk",
        "period": "1st Century CE – Present",
        "era": "Classical to Modern",
        "genre": "Sociological History",
        "literary_tradition": "Maritime History",
        "region": "Southeast Asia, Indian Ocean, Global",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Tamil_diaspora",
        "image_url": "/assets/library/chola_shipbuilding.jpg",
        "image_caption": "Historical maritime route map of Tamil merchant guilds in the Indian Ocean",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3525547) & Maritime Museum Heritage",
        "source_url": "https://www.wikidata.org/wiki/Q3525547",
        "license": "CC BY-SA 4.0",
        "tags": "diaspora,maritime,trade,manigramam,singapore,malaysia,mauritius,global",
        "related_slugs": "rajendra-chola-maritime-expedition,silappathikaram-twin-epics",
    }
]