"""
Seed dataset for Feature 6 — Tamil Literature Library.
Provides structured, source-attributed classical, medieval, and modern Tamil literature entries.
Respects public-domain vs. copyrighted metadata-only rights.
"""

SEED_LITERATURE_ITEMS = [
    # ---------------------------------------------------------------- Sangam & Classical
    {
        "slug": "sangam-literature-anthologies",
        "content_type": "literature",
        "title_ta": "எட்டுத்தொகையும் பத்துப்பாட்டும் (சங்க இலக்கியம்)",
        "title_en": "Ettuthogai & Pattupattu (Sangam Poetic Anthologies)",
        "category": "Classical",
        "summary_ta": "சங்க காலத்தில் புலவர்களால் பாடப்பட்ட அகம் (காதல்) மற்றும் புறம் (வீரம்) சார்ந்த 2,381 செவ்வியல் கவிதைகளின் தொகுப்பு.",
        "summary_en": "The foundational 2,381 classical poems of Tamil literature divided into the Eight Anthologies and Ten Idylls.",
        "content_ta": "சங்க இலக்கியம் என்பது பண்டைத் தமிழர்களின் பண்பாடு, காப்பியம், அகவாழ்க்கை மற்றும் புறவாழ்க்கையை மிகத் தெளிவாக வெளிப்படுத்தும் உன்னத பொக்கிஷமாகும். இது கிமு 300 முதல் கிபி 300 வரையிலான சங்க காலத்தில் வாழ்ந்த பல்வேறு புலவர்களால் இயற்றப்பட்ட பாடல்களின் தொகுப்பாகும். இயற்கை புனைவும், மனித உணர்வுகளின் தூய்மையும் இதன் தனித்துவமான சிறப்பம்சங்களாகும்.\n\nஇத்தொகுப்பு எட்டுத்தொகை மற்றும் பத்துப்பாட்டு என இருபெரும் பிரிவுகளாகப் பிரிக்கப்பட்டுள்ளது. எட்டுத்தொகையில் நற்றிணை, குறுந்தொகை, ஐங்குறுநூறு, பதிற்றுப்பத்து, பரிபாடல், கலித்தொகை, அகநானூறு, புறநானூறு ஆகிய எட்டு அரிய நூல்கள் அடங்கும். பத்துப்பாட்டில் திருமுருகாற்றுப்படை, பொருநராற்றுப்படை, முல்லைப்பாட்டு உள்ளிட்ட பத்து நெடிய நூல்கள் இடம்பெற்றுள்ளன. இவை தமிழர்களின் வீரம், காதல் மற்றும் அறநெறிகளை உலகிற்குப் பறைசாற்றுகின்றன.",
        "content_en": "The Sangam corpus represents the classical foundation of Tamil literature, comprising 2,381 poems meticulously composed by 473 renowned poets. This prestigious group notably includes over 30 celebrated female poets, such as Avvaiyar, Okkur Masathiyar, and Kakkaipadiniyar, highlighting the inclusive literary culture of Ancient Tamilakam.\n\nDivided structurally into Akam (focusing on internal emotions, love, and intricate landscape allegories) and Puram (detailing external social ethics, heroism, governance, and philanthropy), this literature reflects a highly sophisticated secular society. The anthologies are deeply tuned to nature, vividly expressing human experiences through the profound symbolism of the Five Thinaai landscapes: Kurinji, Mullai, Marutham, Neithal, and Palai.",
        "author": "Various Sangam Poets (Avvaiyar, Kapilar, Paranar, etc.)",
        "period": "c. 300 BCE – 300 CE",
        "era": "Sangam Era",
        "genre": "Classical Poetry",
        "literary_tradition": "Sangam",
        "region": "Ancient Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/",
        "image_url": "/assets/library/akanuru_art.jpg",
        "image_caption": "Palm-leaf manuscript heritage of Sangam literary anthologies",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1276701) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q1276701",
        "license": "Public Domain / CC0",
        "tags": "literature,sangam,poetry,ettuthogai,pattupattu,classical",
        "related_slugs": "thirukkural-literary-masterwork,sangam-assembly-foundations",
    },
    {
        "slug": "thirukkural-literary-masterwork",
        "content_type": "literature",
        "title_ta": "திருக்குறள் (உலகப் பொதுமறை)",
        "title_en": "Thirukkural: The Universal Ethical Code",
        "category": "Classical",
        "summary_ta": "திருவள்ளுவரால் இயற்றப்பட்ட அறம், பொருள், இன்பம் என்ற முப்பால்களைக் கொண்ட 1,330 வாழ்வியல் குறள்கள்.",
        "summary_en": "Philosopher Thiruvalluvar's 1,330 couplets establishing universal secular ethics, governance, and human harmony.",
        "content_ta": "திருக்குறள் தமிழ் இலக்கியத்தின் உச்சக்கட்ட சாதனையாகவும், உலகப் பொதுமறையாகவும் போற்றப்படும் ஒரு தலைசிறந்த அறநூலாகும். திருவள்ளுவரால் இயற்றப்பட்ட இந்நூல், 133 அதிகாரங்களில் அதிகாரம் ஒன்றுக்கு 10 குறள்கள் வீதம் மொத்தம் 1,330 சுருக்கமான, ஆனால் ஆழமான பொருட்செறிவு கொண்ட குறட்பாக்களைத் தன்னகத்தே கொண்டுள்ளது.\n\nஇது மூன்று பெரும் பால்களாகப் பிரிக்கப்பட்டுள்ளது: 1) அறத்துப்பால் - தனி மனித ஒழுக்கம் மற்றும் அறநெறிகளைப் போதிக்கிறது; 2) பொருட்பால் - அரசு நிர்வாகம், பொருளாதாரம், நட்பு மற்றும் சிறந்த ஆளுகையை விளக்குகிறது; 3) இன்பத்துப்பால் - தூய காதல் மற்றும் இல்லற அன்பின் மேன்மையைச் சிறப்பிக்கிறது. திருக்குறள் எந்த ஒரு குறிப்பிட்ட மதத்தையோ, சாதியையோ, தேசத்தையோ சார்ந்து நிற்காமல், மனிதகுலம் முழுமைக்குமான உலகளாவிய வாழ்வியல் நீதியை நெறிமுறையாக வழங்குகிறது.",
        "content_en": "Authored by the revered Sage Thiruvalluvar during the Classical Era, the Thirukkural stands as an unparalleled ethical treatise in world literature. Composed in the highly concise Venba meter, consisting of just two lines per couplet, it delivers profound philosophical insights. Its universal appeal is evidenced by its continuous translation into over 40 languages worldwide.\n\nStructurally, it entirely avoids religious or sectarian dogma, choosing instead to address humanity at large with practical wisdom. The 1,330 couplets are meticulously divided across three definitive books: Aram, which explores Virtue and Morality; Porul, detailing Statecraft, Economics, and Public Ethics; and Inbam, which beautifully captures Love and Mutual Loyalty.",
        "author": "Thiruvalluvar",
        "period": "c. 1st – 5th Century CE",
        "era": "Classical Era",
        "genre": "Ethical Philosophy",
        "literary_tradition": "Post-Sangam Ethical",
        "region": "Mylapore / Ancient Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0001.html",
        "image_url": "/assets/library/thirukkural_manuscript.jpg",
        "image_caption": "133-foot Thiruvalluvar Memorial Statue at Kanyakumari",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q312480) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q312480",
        "license": "Public Domain",
        "tags": "literature,thirukkural,thiruvalluvar,ethics,philosophy",
        "related_slugs": "thirukkural-composition,aathichoodi-avvaiyar",
    },
    {
        "slug": "aathichoodi-avvaiyar",
        "content_type": "literature",
        "title_ta": "ஆத்திசூடி (ஔவையார்)",
        "title_en": "Aathichoodi by Avvaiyar",
        "category": "Classical",
        "summary_ta": "ஔவையார் இயற்றிய அகரவரிசையில் அமைந்த 109 நன்னெறி ஓரடி கவிதைகள்.",
        "summary_en": "Poetess Avvaiyar's 109 single-line didactic maxims arranged in Tamil alphabetical order.",
        "content_ta": "ஆத்திசூடி என்பது 12-ஆம் நூற்றாண்டில் வாழ்ந்த தலைசிறந்த தமிழ் பெண் புலவரான ஔவையாரால் இயற்றப்பட்ட ஒரு உன்னதமான அறநூலாகும். இது சிறுவர் முதல் பெரியவர் வரை அனைத்துப் பொதுமக்களுக்கான வாழ்வியல் நெறிகளை மிக எளிய முறையில் எடுத்துரைக்கிறது. தமிழ் அகரவரிசையில் (அ, ஆ, இ, ஈ...) தொடங்கி ஒவ்வொரு வரியும் ஒற்றை அடியாக அமைந்துள்ளது.\n\nஇந்த 109 வரிகளும் மிகச் சுருக்கமாக இருந்தாலும், மிக ஆழமான நன்னெறிகளைப் புகட்டுகின்றன. 'அறம் செய விரும்பு' (அறநெறி செய்ய ஆசைப்படு), 'ஆறுவது சினம்' (கோபத்தைத் தணித்துக் கொள்) போன்ற எளிய வரிகள் இன்றும் பள்ளிகளில் கற்பிக்கப்படுகின்றன. இதன் மூலம் தலைமுறை தலைமுறையாகத் தமிழர்களின் முதல் மற்றும் முதன்மையான பாடநூலாக ஆத்திசூடி தொடர்ந்து திகழ்ந்து வருகிறது.",
        "content_en": "Composed by the legendary female philosopher and poet Avvaiyar during the 12th century, Aathichoodi is a cornerstone of didactic Tamil literature. It uniquely consists of 109 remarkably concise single-line ethical maxims, cleverly arranged in strict accordance with the Tamil alphabet, encompassing both Uyir (vowels) and Uyirmei (consonants) letters.\n\nSpecifically designed for early childhood education and daily life practice, its teachings remain highly relevant today across society. Powerful yet simple lines like 'Aram Seya Virumbu' (Desire to perform righteous deeds) and 'Aaruvathu Sinam' (Cool down anger) are taught to young children, solidifying its place as an integral and enduring part of Tamil moral heritage.",
        "author": "Avvaiyar",
        "period": "c. 12th Century CE",
        "era": "Medieval Period",
        "genre": "Didactic Poetry",
        "literary_tradition": "Ethical Literature",
        "region": "Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0015.html",
        "image_url": "/assets/library/thiruvalluvar_statue.jpg",
        "image_caption": "Statue of Avvaiyar along the Marina Beach promenade, Chennai",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q4829031) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q4829031",
        "license": "Public Domain",
        "tags": "literature,avvaiyar,aathichoodi,didactic,ethics",
        "related_slugs": "thirukkural-literary-masterwork",
    },
    {
        "slug": "silappatikaram-epic-masterwork",
        "content_type": "literature",
        "title_ta": "சிலப்பதிகாரம் (ஐம்பெருங்காப்பியம்)",
        "title_en": "Silappatikaram: The Tale of the Anklet",
        "category": "Classical",
        "summary_ta": "இளங்கோ அடிகளால் இயற்றப்பட்ட தமிழின் முதல் பெரும் காப்பியம் (கோவலன், கண்ணகி, மாதவி வரலாறு).",
        "summary_en": "Prince-monk Ilango Adigal's epic narrative of justice, moral duty, and Kannagi's devotion across three Tamil kingdoms.",
        "content_ta": "சிலப்பதிகாரம் என்பது தமிழ் இலக்கிய வரலாற்றில் தோன்றிய முதல் காப்பியமும், ஐம்பெருங்காப்பியங்களில் முதன்மையானதுமாகும். கி.பி. 5 ஆம் நூற்றாண்டில் சேர நாட்டைச் சேர்ந்த இளங்கோ அடிகள் என்னும் துறவியால் இக்காப்பியம் மிகச் சிறப்பாக இயற்றப்பட்டது. இது முத்தமிழான இயல், இசை, நாடகம் ஆகிய மூன்றையும் தன்னுள் செவ்வனே இணைத்து அழகுற விவரிக்கிறது.\n\nபூம்புகாரைச் சேர்ந்த செல்வந்த வணிகன் கோவலன், அவனது கற்புக்கரசியான மனைவி கண்ணகி மற்றும் ஆடலரசி மாதவி ஆகியோரின் வாழ்க்கைப் பயணமே இதன் மையக்கருவாகும். பாண்டிய மன்னன் நெடுஞ்செழியன் வழங்கிய தவறான தீர்ப்பால் கோவலன் கொல்லப்பட, தன் கற்பின் அதீத சக்தியால் கண்ணகி மதுரையை எரித்த நீதிப் போராட்டத்தை இது கூறுகிறது. 'அரசியல் பிழைத்தோர்க்கு அறம்கூற்றாவதும்' உள்ளிட்ட முப்பெரும் உண்மைகளே இக்காப்பியத்தின் ஆணிவேராகும்.",
        "content_en": "Silappatikaram, famously known as 'The Tale of the Anklet', is a crowning achievement of the Classical Era, authored by the Chera Prince Ilango Adigal. Recognized as the absolute first of the Five Great Epics of Tamil Literature (Aimperumkappiyam), it is celebrated for masterfully weaving together the three core elements of Tamil arts: poetry (Iyal), music (Isai), and theatrical staging (Natakam).\n\nThe epic vividly narrates the tragic yet powerful journey of the merchant Kovalan and his devoted wife Kannagi. Their story traverses the vibrant Poompuhar of the Chola kingdom, the tragic Madurai of the Pandya kingdom, and finally Vanci of the Chera kingdom. Ultimately, the epic immortalizes the profound truth that divine righteousness invariably punishes unjust political authority.",
        "author": "Ilango Adigal",
        "period": "c. 5th Century CE",
        "era": "Classical Era",
        "genre": "Epic Poetry",
        "literary_tradition": "Classical Epic",
        "region": "Poompuhar, Madurai & Vanci",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0010.html",
        "image_url": "/assets/library/silappattikaram_art.jpg",
        "image_caption": "Ancient coastal heritage evoking Poompuhar and Sangam maritime epics",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1276701) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q1276701",
        "license": "Public Domain",
        "tags": "literature,epic,silappatikaram,kannagi,ilango",
        "related_slugs": "silappatikaram-epic,manimekalai-epic",
    },
    {
        "slug": "manimekalai-epic",
        "content_type": "literature",
        "title_ta": "மணிமேகலை (பௌத்தக் காப்பியம்)",
        "title_en": "Manimekalai: The Buddhist Tamil Epic",
        "category": "Classical",
        "summary_ta": "சீத்தலைச் சாத்தனாரால் இயற்றப்பட்ட சிலப்பதிகாரத்தின் தொடர்ச்சியான பௌத்த அறக்கருத்துக்கள் நிறைந்த காப்பியம்.",
        "summary_en": "Sithalai Sathanar's sequel to Silappatikaram detailing Manimekalai's journey into compassion, philosophy, and social service.",
        "content_ta": "மணிமேகலை என்பது ஐம்பெருங்காப்பியங்களில் ஒன்றாகவும், சிலப்பதிகாரத்தின் நேரடித் தொடர்ச்சியாகவும் அமைந்த ஒரு சிறந்த தமிழ் பௌத்தக் காப்பியமாகும். இது மதுரையைச் சேர்ந்த கூலவாணிகன் சீத்தலைச் சாத்தனாரால் செம்மையான நடையில் இயற்றப்பட்டது. கோவலன் மற்றும் மாதவியின் மகளான மணிமேகலையின் துறவு வாழ்க்கையையும் அவளின் தொண்டுகளையும் இக்காப்பியம் விரிவாகப் பேசுகிறது.\n\nஇளம் வயதிலேயே உலக இன்பங்களைத் துறக்கும் மணிமேகலை, மக்களின் பசிப்பிணியைப் போக்க 'அமுதசுரபி' என்ற அமுத பாத்திரத்தைப் பெறுகிறாள். அதன் மூலம் ஏழை எளியோரின் பசியைப் போக்குவதோடு மட்டுமல்லாமல், பல்வேறு பௌத்த தத்துவங்களையும், அறக்கருத்துக்களையும் ஆழமாக விவாதித்து அறிவதையும் இக்காப்பியம் மிகச் சிறந்த காவியமாக நம் கண்முன் நிறுத்துகிறது.",
        "content_en": "Composed by the renowned merchant-poet Sithalai Sathanar, Manimekalai stands as a magnificent Buddhist epic and serves as the direct spiritual sequel to the legendary Silappatikaram. It follows the captivating life of Manimekalai, the daughter of Kovalan and Madhavi, as she consciously rejects a life of courtly luxury and earthly pleasures to adopt strict monastic vows.\n\nDuring her spiritual journey, she is blessed with the 'Amudhasurabi', a divine and inexhaustible alms bowl that miraculously yields endless food for the destitute. Through her remarkable acts of social service, the epic intricately weaves profound philosophical debates encompassing logic, human ethics, and the core tenets of universal Buddhist compassion.",
        "author": "Sithalai Sathanar",
        "period": "c. 6th Century CE",
        "era": "Classical Era",
        "genre": "Epic Poetry / Philosophy",
        "literary_tradition": "Classical Epic",
        "region": "Poompuhar & Kanchipuram",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0024.html",
        "image_url": "/assets/library/manimekalai_art.jpg",
        "image_caption": "Heritage sculptures depicting early philosophical assemblies",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3533608) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q3533608",
        "license": "Public Domain",
        "tags": "literature,manimekalai,epic,buddhism,amudhasurabi",
        "related_slugs": "silappatikaram-epic-masterwork",
    },

    # ---------------------------------------------------------------- Medieval & Bhakti Literature
    {
        "slug": "kambaramayanam-epic",
        "content_type": "literature",
        "title_ta": "கம்பராமாயணம் (ராமாவதாரம்)",
        "title_en": "Kambaramayanam by Kambar",
        "category": "Medieval",
        "summary_ta": "கவிச்சக்கரவர்த்தி கம்பனால் சோழர் காலத்தில் 10,000-க்கும் மேற்பட்ட பாடல்களால் இயற்றப்பட்ட பிரம்மாண்டக் காவியம்.",
        "summary_en": "Kavi Chakravarti Kambar's 12th-century epic masterpiece comprising over 10,000 verses in breathtaking Tamil prosody.",
        "content_ta": "கம்பராமாயணம் என்பது 12-ஆம் நூற்றாண்டில் கவிச்சக்கரவர்த்தி கம்பனால் இயற்றப்பட்ட தமிழ் காவியத்தின் ஈடு இணையற்ற சிகரமாகும். 'கல்வியில் பெரியவன் கம்பன்', மற்றும் 'கம்பன் வீட்டுக்கட்டுத்தறியும் கவிபாடும்' போன்ற புகழ்பெற்ற பழமொழிகள் இக்காப்பியத்தின் கவிதைச் சிறப்பையும், கம்பரின் மொழிப்புலமையையும் காலங்காலமாகப் பறைசாற்றுகின்றன.\n\nஇது பாலகாண்டம் முதல் யுத்தகாண்டம் வரை 6 காண்டங்களைக் கொண்டு, 10,000-க்கும் மேற்பட்ட அற்புதமான சந்தக் கவிதைகளால் கட்டமைக்கப்பட்டுள்ளது. வடமொழியில் உள்ள மூலக் கதையைத் தழுவியிருந்தாலும், தமிழ் பண்பாட்டிற்கும், தமிழர் வாழ்வியலுக்கும், தமிழ்நாட்டின் இயற்கை எழிலுக்கும் ஏற்ப ராமனின் கதையை முற்றிலும் ஒரு புதிய தமிழ்க் காவியமாகவே கம்பர் படைத்துத் தந்துள்ளார்.",
        "content_en": "Authored under the grand patronage of the Chola Empire by the illustrious poet Kambar, Kambaramayanam (originally titled Ramavataram) is universally considered the supreme masterpiece of medieval Tamil poetic virtuosity. Spanning across 6 comprehensive Books (Kandam) and comprising over 10,000 intricate verses predominantly in the complex Virutham meter, it is a monumental literary achievement.\n\nRather than a mere translation, Kambar completely re-imagined the ancient Sanskrit epic to suit the Tamil cultural landscape. He infused the narrative with lush Tamil tropical imagery, profound psychological depth among characters, and extraordinary rhythmic soundscapes that elevate the epic to unprecedented heights of poetic beauty.",
        "author": "Kambar",
        "period": "c. 12th Century CE",
        "era": "Chola Empire",
        "genre": "Epic Poetry",
        "literary_tradition": "Imperial Chola Epic",
        "region": "Thanjavur & Therazhundur",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0040.html",
        "image_url": "/assets/library/kamba_ramayanam.jpg",
        "image_caption": "Imperial Chola temple architecture contemporary to Kambar's era",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3536894) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q3536894",
        "license": "Public Domain",
        "tags": "literature,kambar,kambaramayanam,chola,epic",
        "related_slugs": "chola-rise-vijayalaya,rajaraja-brihadisvara",
    },
    {
        "slug": "thevaram-bhakti-hymns",
        "content_type": "literature",
        "title_ta": "தேவாரம் (திருமுறை பக்திப் பாடல்கள்)",
        "title_en": "Tevaram: Shaivite Devotional Hymns",
        "category": "Bhakti",
        "summary_ta": "திருநாவுக்கரசர், திருஞானசம்பந்தர், சுந்தரர் ஆகிய மூவரால் பண்ணிசையோடு பாடி அருளப்பட்ட பக்தித் தமிழ் பாடல்கள்.",
        "summary_en": "Devotional musical hymns composed by Appar, Sambandar, and Sundarar set to classical Tamil Pan melodies.",
        "content_ta": "தேவாரம் என்பது 7 முதல் 8-ஆம் நூற்றாண்டு வரையிலான பல்லவர் காலத்தில் வாழ்ந்த தலைசிறந்த சிவபக்தர்களான நாயன்மார்களால் பாடப்பட்ட தெய்வீகத் திருமுறைப் பாடல்களின் தொகுப்பாகும். திருஞானசம்பந்தர், திருநாவுக்கரசர் (அப்பர்) மற்றும் சுந்தரமூர்த்தி நாயனார் ஆகிய மூவரால் இவை அழகிய பண்ணிசையோடு பாடி அருளப்பட்டன.\n\nஇவர்கள் தமிழ் மொழியை வெறும் இலக்கியமாக மட்டுமன்றி இசையோடு இணைத்து, ஊர் ஊராகச் சென்று பல்வேறு சிவாலயங்களில் பாடி தமிழ் பக்தி இயக்கத்தை ஆழமாகத் தோற்றுவித்தார்கள். பின்னாளில் நம்பியாண்டார் நம்பியால் 12 திருமுறைகளாகத் தொகுக்கப்பட்ட மாபெரும் பக்தி இலக்கியத்தில், முதல் 7 திருமுறைகளே தேவாரம் எனப் போற்றப்பட்டு இன்றும் கோயில்களில் இசைக்கப்படுகின்றன.",
        "content_en": "Tevaram represents a monumental era of spiritual poetry, referring specifically to the first seven volumes of the Tirumurai, the sacred Shaivite Tamil devotional canon. These 8,227 profound hymns were composed between the 7th and 8th centuries by the three most revered Nayanmars: Saint Sambandar, Appar, and Sundarar.\n\nNotably, these verses were not just read but were masterfully set to ancient Tamil Pan music, intended for melodious recitation. The legendary trio traveled extensively across South Indian temples, democratizing spirituality for the masses and successfully triggering a massive cultural and religious renaissance in Tamil lyricism and devotion.",
        "author": "Appar, Sambandar, Sundarar (Nayanmars)",
        "period": "c. 7th – 8th Century CE",
        "era": "Pallava Period",
        "genre": "Devotional Hymns",
        "literary_tradition": "Bhakti Renaissance",
        "region": "Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0005.html",
        "image_url": "/assets/library/thiruvasagam_art.jpg",
        "image_caption": "Pallava-era temple heritage where Tevaram hymns were composed",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3525547) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q3525547",
        "license": "Public Domain",
        "tags": "literature,thevaram,nayanmar,bhakti,tevaram,music",
        "related_slugs": "bhakti-movement-renaissance,divya-prabandham-alvars",
    },
    {
        "slug": "divya-prabandham-alvars",
        "content_type": "literature",
        "title_ta": "நாலாயிர திவ்வியப் பிரபந்தம் (ஆழ்வார்கள்)",
        "title_en": "Nalayira Divya Prabandham: Vaishnavite Canon",
        "category": "Bhakti",
        "summary_ta": "ஆண்டாள், நம்மாழ்வார் உள்ளிட்ட 12 ஆழ்வார்களால் இயற்றப்பட்ட 4,000 திவ்யப் பிரபந்தக் கவிதைகளின் தொகுப்பு.",
        "summary_en": "The 4,000 divine stanzas composed by the 12 Alvar saints (including poetess Andal and Nammalvar).",
        "content_ta": "நாலாயிர திவ்வியப் பிரபந்தம் என்பது வைணவ சமயத்தின் மிக முக்கிய புனித நூலாகும். இது 6 முதல் 9-ஆம் நூற்றாண்டு காலகட்டத்தில் வாழ்ந்த 12 ஆழ்வார்களால் முழுமையாகத் தமிழில் இயற்றப்பட்ட 4,000 பக்திப் பாசுரங்களின் ஒட்டுமொத்தத் தொகுப்பாகும். காலப்போக்கில் சிதறுண்ட இப்பாடல்களை, நாதமுனிகள் என்பவர் 10-ஆம் நூற்றாண்டில் பெரும் முயற்சி எடுத்து தேடிக் கண்டெடுத்துத் தொகுத்தார்.\n\nஇதில் ஆண்டாள் நாச்சியாரின் 'திருப்பாவை', மற்றும் நம்மாழ்வாரின் 'திருவாய்மொழி' ஆகியவை தமிழ் பக்தி இலக்கியத்தின் விலைமதிப்பற்ற ரத்தினங்களாகக் கருதப்படுகின்றன. திருமாலின் புகழைத் தூய தமிழால் பாடி மகிழ்ந்த ஆழ்வார்களின் இந்த உணர்வுப்பூர்வமான பாடல்கள், வைணவர்களால் 'திராவிட வேதம்' என்று மிகவும் புனிதமாகப் போற்றப்படுகின்றன.",
        "content_en": "The Nalayira Divya Prabandham is the monumental 4,000-verse Tamil devotional canon composed by the 12 supreme Alvar saints. These poetic verses, expressing deep yearning and love for Lord Vishnu, were carefully collected and codified by the scholar Nathamuni during the 10th century, effectively preserving them for future generations.\n\nThis vast collection features unparalleled literary masterpieces, including the revered poetess Andal's mystical 'Thiruppavai' and Nammalvar's philosophically dense 'Tiruvaymoli'. By elevating intense emotional devotion (Bhakti) in the accessible vernacular Tamil language, this body of poetry achieved the exalted and sacred status of the 'Dravida Veda'.",
        "author": "12 Alvars (Andal, Nammalvar, Tirumangai Alvar, etc.)",
        "period": "c. 6th – 9th Century CE",
        "era": "Pallava & Pandya Period",
        "genre": "Devotional Hymns",
        "literary_tradition": "Bhakti Renaissance",
        "region": "Srirangam & Tamilakam",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0012.html",
        "image_url": "/assets/library/abirami_anthathi.jpg",
        "image_caption": "Temple heritage associated with Alvar poetry and Srivilliputhur tower",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3525287) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q3525287",
        "license": "Public Domain",
        "tags": "literature,prabandham,alvar,andal,nammalvar,bhakti",
        "related_slugs": "thevaram-bhakti-hymns,bhakti-movement-renaissance",
    },

    # ---------------------------------------------------------------- Modern & Contemporary
    {
        "slug": "bharathiyar-kavithai-collection",
        "title_ta": "பாரதியார் கவிதைகள் (மகாகவி சுப்பிரமணிய பாரதி)",
        "title_en": "Subramania Bharati: Patriotic & Renaissance Poems",
        "category": "Modern",
        "summary_ta": "சுதந்திரத் தாகம், சமூகச் சமத்துவம், பெண் விடுதலை மற்றும் குழந்தைகளுக்கான நவீன கவிதைகளின் காவியத் தொகுப்பு.",
        "summary_en": "Mahakavi Bharathiyar's seminal modern Tamil poetry collection championing freedom, social equality, and women's empowerment.",
        "content_ta": "மகாகவி சுப்பிரமணிய பாரதியார் (1882-1921) இருபதாம் நூற்றாண்டின் ஒப்பற்ற கவிஞரும், நவீன தமிழ் கவிதையின் பிதாமகனும் ஆவார். இந்தியாவின் காலனி ஆதிக்க காலத்தில் வாழ்ந்த இவர், தனது வீரியமிக்க எழுத்துக்களால் மக்களின் சுதந்திரத் தாகத்தை தட்டி எழுப்பினார். 'வந்தே மாதரம்', 'அச்சமில்லை அச்சமில்லை' போன்ற இவருடைய எழுச்சிமிக்க கவிதைகள் இந்திய சுதந்திரப் போராட்டத்திற்குப் பெரும் புத்துயிர் ஊட்டின.\n\nசுதந்திரம் மட்டுமின்றி, 'பாஞ்சாலி சபதம்', 'குயில் பாட்டு', 'கண்ணன் பாட்டு' போன்ற காவியங்கள் மூலம் சமூக சீர்திருத்தங்களையும் அவர் வலியுறுத்தினார். சாதி ஒழிப்பு, பெண் விடுதலை, சமூகச் சமத்துவம் மற்றும் ஒரு புதிய பாரதத்தின் எழுச்சி ஆகியவற்றை மிக எளிய, இனிய தமிழில் பாமரனுக்கும் புரியும் வண்ணம் பாடித் தமிழ் மொழியை நவீனப்படுத்தினார்.",
        "content_en": "Subramania Bharati (1882–1921), universally and affectionately acclaimed as Mahakavi ('Great Poet'), is widely recognized as the individual who single-handedly revolutionized modern Tamil literature. Combining absolute lyrical mastery with intense nationalist fervor, his poetry ignited a sense of pride and rebellion across the Tamil-speaking world during the Colonial Era.\n\nHis highly influential works—such as 'Panchali Sabatham', 'Kannan Pattu', 'Kuyil Pattu', and 'Papa Pattu'—broke away from rigid classical structures to pioneer free verse (Puthukkavithai). Furthermore, he used his powerful pen to fearlessly champion critical social reforms, demanding caste abolition, widespread education, and women's liberation.",
        "author": "Mahakavi Subramania Bharati",
        "period": "1882 – 1921 CE",
        "era": "Colonial Era",
        "genre": "Modern Nationalist Poetry",
        "literary_tradition": "Modern Independence Renaissance",
        "region": "Ettayapuram, Puducherry & Chennai",
        "copyright_status": "Public Domain",
        "external_link": "https://www.projectmadurai.org/pm_works/pm0002.html",
        "image_url": "/assets/library/periya_puranam.jpg",
        "image_caption": "Literary legacy of Mahakavi Subramania Bharati",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q312480) & Project Madurai",
        "source_url": "https://www.wikidata.org/wiki/Q312480",
        "license": "Public Domain",
        "tags": "literature,bharati,poet,freedom,modern,renaissance",
        "related_slugs": "bharati-nationalist-poetry,reorganization-tamil-nadu",
    },
    {
        "slug": "ponniyin-selvan-kalki",
        "content_type": "literature",
        "title_ta": "பொன்னியின் செல்வன் (கல்கி கிருஷ்ணமூர்த்தி)",
        "title_en": "Ponniyin Selvan by Kalki Krishnamurthy",
        "category": "Modern",
        "summary_ta": "சோழப் பேரரசன் அருள்மொழிவர்மனின் (ராஜராஜ சோழன்) இளமைக் கால வரலாற்றுப் பின்னணியில் கல்கி எழுதிய புகழ்பெற்ற நாவல்.",
        "summary_en": "Kalki Krishnamurthy's legendary historical novel depicting the early life, political intrigue, and rise of Raja Raja Chola I.",
        "content_ta": "பொன்னியின் செல்வன் என்பது நவீன தமிழ் இலக்கிய உலகில் எவராலும் அசைக்க முடியாத புகழ்பெற்ற ஒரு பிரம்மாண்ட வரலாற்று நாவலாகும். புகழ்மிக்க எழுத்தாளர் கல்கி கிருஷ்ணமூர்த்தி அவர்களால் 1950-களில் கல்கி வார இதழில் பல ஆண்டுகளாகத் தொடராக எழுதப்பட்ட இந்த 5 பாகங்களைக் கொண்ட காவியம், இன்றுவரை தமிழ் நாவல் வரலாற்றில் மிக அதிக வாசகர்களால் விரும்பிப் படிக்கப்படும் நூலாகத் திகழ்கிறது.\n\nபத்தாம் நூற்றாண்டின் சோழப் பேரரசைப் பின்னணியாகக் கொண்டு எழுதப்பட்ட இந்நாவல், முதலாம் ராஜராஜ சோழன் (அருள்மொழிவர்மன்) அரியணை ஏறுவதற்கு முன்பிருந்த சிக்கலான அரசியல் சூழ்ச்சிகளை விவரிக்கிறது. வாள்வீரன் வந்தியத்தேவன், அறிவாளியான குந்தவை, பழிவாங்கும் நந்தினி மற்றும் ஒற்றன் ஆழ்வார்க்கடியான் ஆகிய பாத்திரங்களின் சாகசங்களை வரலாற்றுப் பின்னணியோடு மிக விறுவிறுப்பாகவும், சுவாரஸ்யமாகவும் நம் கண்முன் நிறுத்துகிறது.",
        "content_en": "Ponniyin Selvan ('The Son of Ponni / Kaveri') is a breathtaking 5-volume historical fiction masterpiece, brilliantly written by Kalki Krishnamurthy. Originally serialized in the Tamil magazine Kalki throughout the early 1950s, it completely captivated the reading public and remains a monumental achievement in modern Indian literature.\n\nSet against the backdrop of 10th-century Imperial Chola South India, the sprawling narrative follows the charismatic young warrior Vallavaraiyan Vandiyathevan. Through his eyes, readers navigate intense court conspiracies, secret alliances, and royal mysteries surrounding Prince Arulmozhivarman, who would eventually rise to become the great Emperor Raja Raja Chola I. Note: Respected under intellectual property guidelines; metadata, synopsis, and literary context presented for educational exploration.",
        "author": "Kalki Krishnamurthy",
        "period": "1950 – 1954 CE (Set in 10th Century)",
        "era": "Modern Era (Set in Imperial Chola Era)",
        "genre": "Historical Fiction Novel",
        "literary_tradition": "Modern Fiction",
        "region": "Thanjavur, Kadambur & Sri Lanka",
        "copyright_status": "Copyrighted - Metadata & Excerpt Only",
        "external_link": "https://openlibrary.org/works/OL19582279W/Ponniyin_Selvan",
        "image_url": "/assets/library/thirumandhiram_yoga.jpg",
        "image_caption": "Thanjavur royal setting of Kalki's Ponniyin Selvan epic",
        "source_type": "openlibrary",
        "source_name": "Open Library & Ezhuthaani Editorial",
        "source_url": "https://openlibrary.org/works/OL19582279W/Ponniyin_Selvan",
        "license": "Copyrighted - Educational Metadata Only",
        "tags": "literature,kalki,ponniyinselvan,novel,chola,history",
        "related_slugs": "rajaraja-brihadisvara,chola-rise-vijayalaya",
    },
]