"""
Seed dataset for Feature 7 — Tamil Script History.
Provides structured, source-attributed historical stages of Tamil writing evolution:
Tamil-Brahmi -> Vatteluttu -> Pallava Grantha -> Imperial Chola -> Later Medieval -> Modern Tamil.
Uses content_type = "script_history".
"""

SEED_SCRIPT_HISTORY_ITEMS = [
    {
        "slug": "tamil-brahmi-phase",
        "content_type": "script_history",
        "title_ta": "தமிழி (தமிழ் பிராமி) எழுத்து முறைமை",
        "title_en": "Tamizhi (Tamil-Brahmi) Script Phase",
        "category": "Script History",
        "summary_ta": "கி.மு. 3-ஆம் நூற்றாண்டு முதல் கி.பி. 3-ஆம் நூற்றாண்டு வரை பயன்பாட்டில் இருந்த தமிழின் மிகப்பழமையான வரிவடிவம்.",
        "summary_en": "The oldest deciphered epigraphic script of Tamil, incised on cave beds, pottery, and rock shelters across Tamilakam.",
        "content_ta": "தமிழி அல்லது தமிழ் பிராமி என்பது தமிழ் மொழியை எழுதப் பயன்படுத்தப்பட்ட முதன்மை வரிவடிவமாகும். மதுரை மாங்குளம், புகழூர், கொடுமணல் மற்றும் கீழடி ஆகிய இடங்களில் கண்டெடுக்கப்பட்ட பிராமி கல்வெட்டுகள் மற்றும் பானை ஓடுகள் மூலம் தமிழின் எழுத்து மரபு கி.மு. 3-ஆம் நூற்றாண்டுக்கு முற்பட்டது என்பது உறுதியாகியுள்ளது. வடமொழி பிராமி போலன்றி, தமிழில் மெய்யெழுத்துக்களைக் குறிக்க 'புள்ளி' (Pulli) இடும் தனித்துவமான முறை தொல்காப்பிய இலக்கண விதிகளை ஒட்டி அமைந்திருந்தது.",
        "content_en": "Tamil-Brahmi (referred to as Tamizhi in classical texts) is an abugida script derived specifically for Tamil phonology. Unlike Ashokan Brahmi, Tamil-Brahmi accommodated distinct Dravidian sounds like ழ (ḻa), ள (ḷa), ற (ṟa), and ன (ṉa), and introduced the Pulli (diacritical dot) to suppress inherent vowels. Over 90 cave inscriptions on natural granite hills (such as Mangulam, Alagarmalai, Sittannavasal) and hundreds of potsherds from Keezhadi prove widespread literacy during the Sangam age.",
        "author": "Epigraphy & Palaeography Research Group",
        "period": "c. 300 BCE – 300 CE",
        "era": "Sangam Era",
        "genre": "Epigraphic History",
        "literary_tradition": "Palaeography",
        "region": "Tamilakam (Madurai, Kongu, Vaigai)",
        "script": "Tamil-Brahmi",
        "script_language": "Tamil",
        "historical_significance": "Established the earliest written literacy in South Asia outside the Indus Valley, proving widespread public literacy in Sangam urban centers.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Tamil-Brahmi",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Tamil_Brahmi_Mangulam.jpg/800px-Tamil_Brahmi_Mangulam.jpg",
        "image_caption": "3rd Century BCE Tamil-Brahmi cave inscription at Mangulam, Madurai",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q2073426) & Archaeological Survey of India",
        "source_url": "https://www.wikidata.org/wiki/Q2073426",
        "license": "CC BY-SA 4.0",
        "tags": "script,brahmi,tamizhi,mangulam,keezhadi,epigraphy,sangam",
        "related_slugs": "mangulam-tamil-brahmi-inscription,keezhadi-brahmi-potsherd-names,tolkappiyam-grammatical-tradition",
    },
    {
        "slug": "vatteluttu-phase",
        "content_type": "script_history",
        "title_ta": "வட்டெழுத்து வரிவடிவ வளர்ச்சி",
        "title_en": "Vatteluttu (Round Script) Development",
        "category": "Script History",
        "summary_ta": "கி.பி. 4-ஆம் நூற்றாண்டு முதல் 8/9-ஆம் நூற்றாண்டு வரை சேர மற்றும் பாண்டிய நாடுகளில் விரிவாகப் பயன்படுத்தப்பட்ட வளைந்த வரிவடிவம்.",
        "summary_en": "The cursive 'round script' characterized by fluid circular strokes, widely used for palm-leaf incising and rock inscriptions.",
        "content_ta": "வட்டெழுத்து என்பது தமிழ் பிராமி எழுத்துக்களிலிருந்து படிமுறை வளர்ச்சியடைந்த ஒரு வளைந்த தமிழ் வரிவடிவமாகும். பனை ஓலைகளில் எழுத்தாணி கொண்டு வேகமாக எழுதும்போது ஓலைகள் கிழியாமல் இருக்க நேர்கோடுகளுக்குப் பதிலாக வட்ட வடிவக் கோடுகள் பயன்படுத்தப்பட்டதால் இது 'வட்டெழுத்து' எனப் பெயர் பெற்றது. சேர நாடான കേരളத்திலும், தென் தமிழகத்தின் பாண்டிய நாட்டிலும் 8/9-ஆம் நூற்றாண்டு வரை இச்சுவடி மரபு முதன்மையாக விளங்கியது.",
        "content_en": "Vatteluttu ('Round Script') evolved directly from Tamil-Brahmi around the 4th century CE. Designed to accommodate swift scribal writing with an iron stylus on fragile palm leaves without tearing the fiber, straight angles transformed into sweeping curves. It remained the official administrative script of the Chera and Pandya kingdoms until Rajaraja Chola I standardized the Chola-Tamil script in the 11th century. Vatteluttu also formed the basis of the Malayalam script.",
        "author": "Manuscript & Epigraphy Desk",
        "period": "c. 400 CE – 800/900 CE",
        "era": "Post-Sangam to Medieval",
        "genre": "Scribal History",
        "literary_tradition": "Palaeography",
        "region": "Pandya Kingdom & Chera Country (Kerala)",
        "script": "Vatteluttu",
        "script_language": "Tamil",
        "historical_significance": "Demonstrates the practical adaptation of writing media (iron stylus on palm leaves) shaping script aesthetics and forming the ancestor of Kerala Malayalam writing.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Vatteluttu",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Vatteluttu hero stone inscription from Chengam",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q2034907) & Kerala State Archives",
        "source_url": "https://www.wikidata.org/wiki/Q2034907",
        "license": "CC BY-SA 4.0",
        "tags": "script,vatteluttu,round_script,pandya,chera,palm_leaf,hero_stone",
        "related_slugs": "hero-stones-nadukal-tradition,palm-leaf-manuscripts-preservation,srirangam-pandyan-copper-plates",
    },
    {
        "slug": "pallava-grantha-phase",
        "content_type": "script_history",
        "title_ta": "பல்லவர் காலம் மற்றும் கிரந்த எழுத்துக் கலப்பு",
        "title_en": "Pallava Script & Grantha Integration Phase",
        "category": "Script History",
        "summary_ta": "கி.பி. 4 முதல் 8-ஆம் நூற்றாண்டுகளில் பல்லவர் ஆட்சியில் மலர்ந்த அலங்காரக் கல்வெட்டு எழுத்துக்களும் கிரந்த எழுத்து அறிமுகமும்.",
        "summary_en": "The majestic box-headed and cursive script styles introduced by Pallava kings, alongside Grantha characters for Sanskrit loanwords.",
        "content_ta": "பல்லவர் காலத்தில் (கி.பி. 400 - 800) தமிழ் எழுத்து வடிவம் புதிய கலைநயமிக்க திருப்புமுனையைப் பெற்றது. மகேந்திரவர்மன் மற்றும் நரசிம்மவர்மன் ஆகிய பல்லவ மன்னர்கள் மாமல்லபுரம் குடைவரைகளிலும் காஞ்சிபுரம் கோயில்களிலும் செதுக்கிய கல்வெட்டுகள் செவ்வக வடிவிலான நுட்பமான எழுத்துக்களால் ஆனவை. இதே காலத்தில் வடமொழிச் சொற்களையும் ஒலிப்புகளையும் எழுத 'கிரந்த எழுத்துக்கள்' (Grantha Script) உருவாக்கப்பட்டு தமிழோடு இணைந்து பயன்படுத்தப்பட்டன.",
        "content_en": "Under the Pallava dynasty (4th–8th centuries CE), Tamil script underwent stylistic refinement in stone carving. Pallava inscriptions displayed ornate 'box-headed' serifs and symmetrical flourishes seen at Mamallapuram and Kanchipuram Kailasanathar temple. Concurrently, South Indian scribes developed the Grantha script to write Sanskrit texts. Characters like ஜ (ja), ஷ (ṣa), ஸ (sa), ஹ (ha), and க்ஷ (kṣa) were introduced into Tamil usage to transcribe Sanskrit borrowings without altering native Tamil phonology.",
        "author": "Pallava Art History Desk",
        "period": "c. 400 CE – 800 CE",
        "era": "Pallava Period",
        "genre": "Royal Epigraphy",
        "literary_tradition": "Palaeography",
        "region": "Tondaimandalam (Kanchipuram, Mamallapuram)",
        "script": "Pallava Grantha / Pallava Tamil",
        "script_language": "Tamil & Sanskrit",
        "historical_significance": "Introduced ornamental architectural typography and established Grantha letters that extended the phonetic range of Tamil script across Southeast Asia.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Pallava_script",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Mamallapuram_Mahabalipuram_Ratha.jpg/800px-Mamallapuram_Mahabalipuram_Ratha.jpg",
        "image_caption": "Pallava Grantha foundation inscription at Kanchipuram Kailasanathar Temple",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q2069806) & Archaeological Survey of India",
        "source_url": "https://www.wikidata.org/wiki/Q2069806",
        "license": "CC BY-SA 4.0",
        "tags": "script,pallava,grantha,mamallapuram,kanchipuram,inscriptions",
        "related_slugs": "mahabalipuram-rock-cut-inscriptions,kudumiyanmalai-musical-inscription,pallava-rock-cut-architecture",
    },
    {
        "slug": "chola-chola-script-phase",
        "content_type": "script_history",
        "title_ta": "சோழர் காலச் செம்மொழி எழுத்துச் சீரமைப்பு",
        "title_en": "Imperial Chola Script Standardization",
        "category": "Script History",
        "summary_ta": "ராஜராஜ சோழன் காலத்தில் தஞ்சைப் பெரிய கோயிலிலும் செப்புப் பட்டயங்களிலும் செதுக்கப்பட்ட தெளிவான சோழத் தமிழ் எழுத்து முறை.",
        "summary_en": "The royal standardization of Tamil script under Imperial Cholas, replacing Vatteluttu in northern Tamilakam with high-contrast granite carving.",
        "content_ta": "பிற்காலச் சோழப் பேரரசு காலத்தில் (கி.பி. 9-13 ஆம் நூற்றாண்டு) தமிழ் எழுத்துக்கள் நாடு முழுவதும் ஒரே மாதிரியான வடிவியல் சீரமைப்பைப் பெற்றன. முதலாம் ராஜராஜ சோழன் மற்றும் ராஜேந்திர சோழன் ஆகியோர் தஞ்சைப் பெரிய கோயில் மற்றும் கங்கைகொண்ட சோழபுரம் சுவர்களில் ஆயிரக்கணக்கான கல்வெட்டு வரிகளைச் செதுக்கினர். வட்டெழுத்திற்குப் பதிலாகத் தெளிவான சோழத் தமிழ் எழுத்துக்கள் அரசு ஆவணமாக மாற்றப்பட்டன.",
        "content_en": "The Imperial Chola period (9th–13th centuries CE) unified regional scribal variations into a cohesive national script. King Raja Raja Chola I mandated the use of Chola-Tamil script across all administrative edicts, temple land grants, and copper plates (such as the Karandai and Tiruvalangadu plates). The deep V-cut granite stone engraving style produced sharp, highly legible letterforms that directly anticipated modern printed Tamil.",
        "author": "Chola Epigraphy Desk",
        "period": "c. 850 CE – 1279 CE",
        "era": "Chola Empire",
        "genre": "Imperial Standardization",
        "literary_tradition": "Palaeography",
        "region": "Thanjavur, Gangaikondacholapuram, Chola Realm",
        "script": "Chola Tamil",
        "script_language": "Tamil",
        "historical_significance": "Standardized script across South India and maritime Southeast Asia, creating the direct visual forerunner of modern printed Tamil script.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Tamil_script",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Brihadeeswarar_Temple_Tanjavur.jpg/800px-Brihadeeswarar_Temple_Tanjavur.jpg",
        "image_caption": "Chola-Tamil granite inscriptions on the base of Tanjavur Brihadisvara Temple",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1078750) & Tanjavur Palace Library",
        "source_url": "https://www.wikidata.org/wiki/Q1078750",
        "license": "CC BY-SA 4.0",
        "tags": "script,chola,tanjavur,rajaraja,epigraphy,granite,copper_plates",
        "related_slugs": "tanjavur-big-temple-inscription,uttiramerur-chola-election-inscription,chola-rise-vijayalaya",
    },
    {
        "slug": "later-tamil-reforms-phase",
        "content_type": "script_history",
        "title_ta": "அச்சு எந்திரமும் வீரமாமுனிவரின் எழுத்துச் சீர்திருத்தமும்",
        "title_en": "Printing Press & Costanzo Beschi's Orthographic Reforms",
        "category": "Script History",
        "summary_ta": "18-ஆம் நூற்றாண்டில் அச்சு எந்திரப் பயன்பாட்டிற்காக வீரமாமுனிவர் (Beschi) மேற்கொண்ட குறில், நெடில் மற்றும் ஏகார, ஓகார சீர்திருத்தங்கள்.",
        "summary_en": "18th-century innovations introduced by Italian Tamil scholar Constanzo Beschi to distinguish short and long vowels for wooden movable type.",
        "content_ta": "அச்சு எந்திரங்களின் வருகையால் தமிழ் எழுத்து வடிவத்தில் மிகப்பெரிய சீர்திருத்தங்கள் தேவைப்பட்டன. 18-ஆம் நூற்றாண்டில் இத்தாலி நாட்டிலிருந்து தமிழகம் வந்த கான்ஸ்டான்டின் ஜோசப் பெஸ்கி (வீரமாமுனிவர்) தமிழ் அச்சுக்கலைக்கு ஏற்றவாறு 'எ' மற்றும் 'ஏ', 'ஒ' மற்றும் 'ஓ' ஆகிய குறில் நெடில் உயிர் எழுத்துக்களின் தலைப்பகுதியிலும் சுழியிலும் மாறுபாடுகளைச் செய்தார். மேலும், மெய்யெழுத்துக்களின் மேல் புள்ளி வைக்கும் முறையை அச்சுக்கு ஏற்பத் தெளிவுபடுத்தினார்.",
        "content_en": "With the introduction of printing presses in Goa and Tranquebar (Tharangambadi) by European missionaries, handwritten manuscript conventions presented challenges for metal type founding. In 1730, Italian Jesuit scholar Costanzo Giuseppe Beschi (known as Veeramamunivar) introduced critical orthographic reforms: he added loop markers to distinguish short 'எ' and long 'ஏ', and short 'ஒ' and long 'ஓ', eliminating ambiguity in printed prose.",
        "author": "Print History & Orthography Group",
        "period": "c. 1556 CE – 1800 CE",
        "era": "Colonial Era",
        "genre": "Orthographic Reform",
        "literary_tradition": "Typography & Printing",
        "region": "Tranquebar (Tharangambadi) & Madurai",
        "script": "Printed Modernizing Tamil",
        "script_language": "Tamil",
        "historical_significance": "Pioneered font design adaptations that allowed Tamil to become the first non-European language to enter modern typography and print culture.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Constanzo_Beschi",
        "image_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Early printed Tamil manuscript from the Ziegenbalg press at Tranquebar",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q713600) & Tranquebar Museum Archives",
        "source_url": "https://www.wikidata.org/wiki/Q713600",
        "license": "CC BY-SA 4.0",
        "tags": "script,print,veeramamunivar,beschi,tranquebar,orthography,typefounding",
        "related_slugs": "palm-leaf-manuscripts-preservation,bharathiyar-kavithaigal",
    },
    {
        "slug": "modern-tamil-script-phase",
        "content_type": "script_history",
        "title_ta": "பெரியார் எழுத்துச் சீர்திருத்தமும் தற்காலத் தமிழ் (247 எழுத்துக்கள்)",
        "title_en": "Periyar Script Reform & Modern 247-Letter Tamil Standard",
        "category": "Script History",
        "summary_ta": "1935-இல் பெரியார் முன்மொழிந்து 1978-இல் தமிழக அரசால் நடைமுறைப்படுத்தப்பட்ட தற்காலத் தமிழ் எழுத்துச் சீரமைப்பு.",
        "summary_en": "The modern script reform proposed by Periyar E. V. Ramasamy in 1935 and officially adopted in 1978, simplifying ணா, ணை, றா, றை, னா, னை characters.",
        "content_ta": "தற்காலத் தமிழ் எழுத்து வடிவம் 12 உயிரெழுத்துக்கள், 18 மெய்யெழுத்துக்கள், 216 உயிர்மெய் எழுத்துக்கள் மற்றும் 1 ஆய்த எழுத்து என மொத்தம் 247 எழுத்துக்களைக் கொண்டது. 1935-இல் பெரியார் ஈ.வெ.ரா 'விடுதலை' இதழில் ணா, ணை, ணொ, ணோ, றா, றை, னா, னை போன்ற சிக்கலான சுழி வரிவடிவங்களை எளிமைப்படுத்தி முன்மொழிந்தார். இச்சீர்திருத்தத்தை 1978-இல் தந்தை பெரியார் நூற்றாண்டு விழாவையொட்டி எம்.ஜி.ராமச்சந்திரன் தலைமையிலான தமிழக அரசு அதிகாரப்பூர்வமாக நடைமுறைப்படுத்தியது.",
        "content_en": "The contemporary Tamil script consists of 12 Vowels (Uyir), 18 Consonants (Mei), 216 Vowel-Consonant combinations (Uyirmei), and 1 Special Character (Aaydha Ezhuthu - ஃ), totaling 247 characters. In 1935, social reformer Periyar E. V. Ramasamy proposed rationalizing complex ligatures (such as ணா, ணை, றா, றை, னா, னை) into consistent post-script modifier strokes. In 1978, the Government of Tamil Nadu officially adopted this reform for education, newspapers, and digital computing.",
        "author": "Modern Tamil Orthography Commission",
        "period": "1935 CE – Present",
        "era": "Modern Era",
        "genre": "Digital & Typography Reform",
        "literary_tradition": "Modern Orthography",
        "region": "Tamil Nadu, Sri Lanka, Singapore, Global",
        "script": "Modern Tamil (Unicode U+0B80–U+0BFF)",
        "script_language": "Tamil",
        "historical_significance": "Simplified Tamil printing and typewriter keymaps, paving the way for digital encoding in Unicode and international computer fonts.",
        "copyright_status": "Public Domain",
        "external_link": "https://en.wikipedia.org/wiki/Tamil_script#Script_reform",
        "image_url": "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "The modern 247-character Tamil Uyirmei script matrix used in digital typography",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1078750) & Tamil Virtual Academy",
        "source_url": "https://www.wikidata.org/wiki/Q1078750",
        "license": "CC BY-SA 4.0",
        "tags": "script,modern,periyar,reform,unicode,typography,247_letters",
        "related_slugs": "tolkappiyam-grammatical-tradition,reorganization-tamil-nadu,classical-language-declaration",
    }
]
