"""
Seed dataset for Feature 4 — Tamil Culture Explorer.
Provides structured, source-attributed cultural entries across 8 core categories.
"""

SEED_CULTURAL_ITEMS = [
    # ---------------------------------------------------------------- Food
    {
        "slug": "pongal-dish",
        "title_ta": "பொங்கல் உணவு",
        "title_en": "Pongal (Venn & Sakkarai)",
        "category": "Food",
        "summary_ta": "அரிசி, பருப்பு, நெய் மற்றும் முந்திரி சேர்த்து செய்யப்படும் பாரம்பரிய தமிழர்களின் அறுவடை உணவு.",
        "summary_en": "Traditional Tamil harvest dish made of freshly harvested rice, moong dal, ghee, nuts, and jaggery.",
        "content_ta": "பொங்கல் தமிழ்நாட்டின் மிகவும் புகழ்பெற்ற பாரம்பரிய உணவாகும். தையல் திங்களில் அறுவடை செய்யப்படும் புதிய அரிசியை மண்பானையில் இட்டு பாலுடன் கொதிக்க வைத்து பொங்க விடுவது வழக்கம். இதில் இனிப்புச் சுவை கொண்ட சர்க்கரைப் பொங்கலும், காரச் சுவை கொண்ட வெண் பொங்கலும் அடங்கும். ஆரோக்கியமான தானியங்கள் மற்றும் நறுமணப் பொருட்கள் நிறைந்தது.",
        "content_en": "Pongal is the flagship culinary identity of Tamil Nadu. Prepared during the harvest month of Thai, new rice is boiled with milk in traditional earthenware pots until it overflows, symbolizing overflowing prosperity. It has two main variants: Sakkarai Pongal (sweet, prepared with organic jaggery and cardamom) and Venn Pongal (savory, tempered with cumin, black pepper, ginger, and ghee).",
        "region": "Tamil Nadu",
        "period": "Ancient to Modern",
        "location_name": "Madurai Harvest Belt, Tamil Nadu",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "image_url": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Traditional Tamil Pongal served on fresh banana leaf",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1528659) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1528659",
        "license": "CC BY-SA 4.0 / CC0",
        "tags": "food,culinary,harvest,pongal,traditional",
    },
    {
        "slug": "idli-dosa",
        "title_ta": "இட்லி மற்றும் தோசை",
        "title_en": "Idli & Dosa",
        "category": "Food",
        "summary_ta": "அரிசி மற்றும் உளுந்து மாவை நொதிக்க வைத்து செய்யப்படும் தென்னிந்தியாவின் முதன்மை காலை உணவு.",
        "summary_en": "Steam-cooked rice cakes and crispy fermented crepes served with coconut chutney and sambar.",
        "content_ta": "இட்லியும் தோசையும் தமிழர்களின் அன்றாட வாழ்வின் இன்றியமையாத உணவுகள். அரிசியும் உளுந்தும் ஊறவைத்து அரைக்கப்பட்டு, இயற்கையான முறையில் நொதிக்க வைக்கப்படுகிறது. ஆவியில் வேகவைக்கப்படும் இட்லி மிகவும் எளிதில் செரிமானமாகும் சத்தான உணவாகும். தோசை நெய்யுடன் பொன்னிறமாக சுடப்பட்டு தேங்காய் சட்னி மற்றும் சாம்பாருடன் பரிமாறப்படுகிறது.",
        "content_en": "Idli and Dosa represent the hallmark of South Indian fermented food science. Rice and urad dal are soaked, ground into a smooth batter, and naturally fermented overnight. Steamed idlis are globally renowned for their gut-friendly digestibility, while crispy golden dosas offer a delight when paired with coconut chutney and piping hot sambar.",
        "region": "Tamil Nadu & South India",
        "period": "Classical to Modern",
        "location_name": "Chennai Heritage Culinary Center, Tamil Nadu",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Crispy golden Dosa and soft steamed Idli with chutneys",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q847625) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q847625",
        "license": "CC BY-SA 4.0",
        "tags": "food,breakfast,dosa,idli,fermented",
    },

    # ---------------------------------------------------------------- Festivals
    {
        "slug": "thai-pongal",
        "title_ta": "தாய் பொங்கல் விழா",
        "title_en": "Thai Pongal Harvest Festival",
        "category": "Festivals",
        "summary_ta": "இயற்கைக்கும் சூரியனுக்கும் நன்றி தெரிவிக்கும் தமிழர்களின் முதன்மை அறுவடைத் திருநாள்.",
        "summary_en": "Four-day Tamil solar harvest festival dedicated to the Sun God Surya and agricultural cattle.",
        "content_ta": "தைப்பொங்கல் தமிழர்களின் தலையாய பண்பாட்டுத் திருவிழாவாகும். இது தை மாதத்தின் முதல் நாளில் கொண்டாடப்படுகிறது. முதல் நாள் போகி பண்டிகை (பழையன கழித்தல்), இரண்டாம் நாள் தாய் பொங்கல் (சூரியனுக்கு நன்றி தெரிவித்தல்), மூன்றாம் நாள் மாட்டுப் பொங்கல் (உழவுக்கு உதவும் கால்நடைகளுக்கு மதிப்பளித்தல்), நான்காம் நாள் காணும் பொங்கல் (உறவினர்களைச் சந்தித்தல்) என நான்கு நாட்கள் சிறப்பாகக் கொண்டாடப்படுகிறது.",
        "content_en": "Thai Pongal is the quintessential multi-day Thanksgiving festival of the Tamil people. Celebrated on the first day of the Tamil month Thai, it honors Surya (Sun God) and Mother Nature for agricultural abundance. The festival spans four distinct days: Bhogi (discarding old items), Thai Pongal (cooking the harvest rice), Maattu Pongal (decorating and honoring farm cattle), and Kaanum Pongal (reuniting with extended family).",
        "region": "Global Tamil Diaspora",
        "period": "Annual Solar Event (January)",
        "location_name": "Thanjavur Delta Farmlands, Tamil Nadu",
        "latitude": 10.7870,
        "longitude": 79.1378,
        "image_url": "https://images.unsplash.com/photo-1610057099443-f63a44509c23?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Sugarcane and traditional pot decorated for Thai Pongal",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1146283) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1146283",
        "license": "CC BY-SA 4.0",
        "tags": "festival,pongal,harvest,sun,thai",
    },
    {
        "slug": "puthandu",
        "title_ta": "தமிழ் புத்தாண்டு (சித்திரை 1)",
        "title_en": "Puthandu (Tamil New Year)",
        "category": "Festivals",
        "summary_ta": "சித்திரை மாதத்தின் முதல் நாளில் தொடங்கும் தமிழ் சூரிய நாட்காட்டியின் புத்தாண்டு விழா.",
        "summary_en": "The Tamil solar New Year celebrated on the first day of Chithirai with fruit displays and traditional feasts.",
        "content_ta": "சித்திரை முதல் நாள் தமிழ் புத்தாண்டாகக் கொண்டாடப்படுகிறது. இந்நாளில் வீடுகளின் வாசலில் அழகிய கோலமிட்டு, மா, பலா, வாழை ஆகிய முக்கனிகள், மலர்கள், நகைகள் அடங்கிய 'கண்ணி' அமைத்து புத்தாண்டை வரவேற்பார்கள். வேப்பம்பூ பச்சடி செய்து இனிப்பும் கசப்பும் கலந்த வாழ்க்கையின் தத்துவத்தை உணர்ந்து உண்பது சிறப்பம்சமாகும்.",
        "content_en": "Puthandu marks the commencement of the new cycle in the traditional Tamil solar calendar on mid-April. Families arrange 'Kanni'—a auspicious tray featuring three royal fruits (mango, jackfruit, banana), betel leaves, gold, and mirrors to gaze upon at sunrise. A unique dish named Veppam Poo Pachadi (made with neem flowers, jaggery, and tamarind) is consumed to remind learners that life is a balanced harmony of sweet, bitter, and sour experiences.",
        "region": "Tamil Nadu & Sri Lanka",
        "period": "Annual Solar Event (April 14)",
        "location_name": "Chidambaram Cultural Sanctuary, Cuddalore",
        "latitude": 11.3992,
        "longitude": 79.6934,
        "image_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Traditional lamps and floral rangoli set for Puthandu",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3525287) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3525287",
        "license": "CC BY-SA 4.0",
        "tags": "festival,newyear,chithirai,puthandu",
    },

    # ---------------------------------------------------------------- Arts
    {
        "slug": "bharatanatyam",
        "title_ta": "பரதநாட்டியம்",
        "title_en": "Bharatanatyam",
        "category": "Arts",
        "summary_ta": "பாவம், ராகம், தாளம் ஆகியவை இணைந்த தென்னிந்தியாவின் தொன்மையான செவ்வியல் நடனக் கலை.",
        "summary_en": "One of India's oldest classical dance forms, expressing spiritual themes through mudras and rhythmic footwork.",
        "content_ta": "பரதநாட்டியம் தமிழ்நாட்டின் கோவில்களில் தோன்றி வளர்ந்த உலகப் புகழ்பெற்ற நடனக் கலையாகும். 'ப' என்பது பாவம் (உணர்ச்சி), 'ர' என்பது ராகம் (இசை), 'த' என்பது தாளம் (கால அளவு) ஆகியவற்றைக் குறிக்கிறது. நிருத்தம் (சுத்த நடனம்), நிருத்தியம் (கருத்து நடனம்), நாட்டியம் (நாடகம்) ஆகிய மூன்றையும் உள்ளடக்கிய இக்கலை நடராஜ பெருமானின் தாண்டவத் தத்துவத்துடன் தொடர்புடையது.",
        "content_en": "Bharatanatyam is a major Indian classical dance that originated in the sacred temples of Tamil Nadu. The name is a composite of Bha (Bhava / emotion), Ra (Raga / melody), and Ta (Tala / rhythm). Dancers utilize intricate facial abhinaya, stylized hand gestures (mudras), and sharp geometric postures to communicate divine narratives and philosophical epics.",
        "region": "Tamil Nadu",
        "period": "Ancient Origins (Codified by Natya Shastra)",
        "location_name": "Thanjavur Classical Dance Academies, Tamil Nadu",
        "latitude": 10.7870,
        "longitude": 79.1378,
        "image_url": "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Bharatanatyam dancer performing traditional temple mudras",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q324083) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q324083",
        "license": "CC BY-SA 4.0",
        "tags": "arts,dance,classical,bharatanatyam,temple",
    },
    {
        "slug": "karagattam",
        "title_ta": "கரகாட்டம்",
        "title_en": "Karagattam Folk Dance",
        "category": "Arts",
        "summary_ta": "தலையில் அலங்கரிக்கப்பட்ட பித்தளைச் செம்பை ஏந்தி ஆடப்படும் தமிழ் கிராமிய நாட்டுப்புறக் கலை.",
        "summary_en": "Ancient Tamil folk dance where performers balance decorated brass pots atop their heads to rhythmic folk beats.",
        "content_ta": "கரகாட்டம் தமிழ்நாட்டின் மிகவும் புகழ்பெற்ற நாட்டுப்புற நடன வடிவமாகும். மழைக்கடவுளான மாரியம்மனை வழிபடவும் கொண்டாட்டங்களுக்கும் இது ஆடப்படுகிறது. நடனக் கலைஞர்கள் பச்சரிசி அல்லது மணல் நிரப்பப்பட்ட கரகத்தை (பித்தளை பாத்திரம்) தலையில் சமநிலைப்படுத்தி நயம்பட ஆடுவார்கள். நையாண்டி மேளம் மற்றும் தவில் இசையின் பின்னணியில் இது நிகழ்த்தப்படுகிறது.",
        "content_en": "Karagattam is a joyful Tamil folk dance celebrating rain and river deities. Performers balance heavy brass pots (Karagam) adorned with flowers and a wooden parrot atop their heads while performing acrobatic feats without touching the vessel. Accompanied by Nayyandi Melam folk drums, it showcases astounding physical equilibrium and rhythmic mastery.",
        "region": "Rural Tamil Nadu",
        "period": "Traditional Folk Era",
        "location_name": "Madurai Folk Performing Grounds, Tamil Nadu",
        "latitude": 9.9172,
        "longitude": 78.1228,
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Folk instruments and vibrant attire used in Karagattam performance",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q6367732) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q6367732",
        "license": "CC BY-SA 4.0",
        "tags": "arts,folk,karagattam,dance,music",
    },

    # ---------------------------------------------------------------- Architecture
    {
        "slug": "brihadisvara-temple",
        "title_ta": "தஞ்சைப் பெரிய கோவில் (பிரகதீஸ்வரர்)",
        "title_en": "Brihadisvara Temple, Thanjavur",
        "category": "Architecture",
        "summary_ta": "முதலாம் ராஜராஜ சோழனால் கி.பி. 1010-இல் கட்டப்பட்ட யுனெஸ்கோ உலகப் பாரம்பரிய திராவிடக் கற்கோவில்.",
        "summary_en": "11th-century UNESCO World Heritage granite temple built by Emperor Raja Raja Chola I, featuring a monolithic vimana spire.",
        "content_ta": "தஞ்சாவூர் பிரகதீஸ்வரர் கோவில் (பெரிய கோவில்) சோழர் கட்டிடக்கலையின் உச்சகட்ட சாதனையாகும். கி.பி. 1010-இல் ராஜராஜ சோழனால் கட்டி முடிக்கப்பட்ட இக்கோவில் முற்றிலும் கருங்கற்களால் ஆனது. இதன் 216 அடி உயர விமானத்தின் உச்சியில் உள்ள 80 டன் எடையுள்ள ஒரே கல்லால் ஆன சிகரம் கட்டிடக்கலை அதிசயமாகும். இதன் சுவர்களில் வரையப்பட்டுள்ள சோழர் கால ஓவியங்கள் வரலாற்றுச் சிறப்புமிக்கவை.",
        "content_en": "The Brihadisvara Temple in Thanjavur is a masterpiece of Dravidian granite architecture constructed by Emperor Raja Raja Chola I in 1010 CE. Recognized as a UNESCO World Heritage monument, it boasts a 66-meter high Vimana tower topped by an 80-ton monolithic granite cupola that was elevated using a kilometers-long earthen ramp.",
        "region": "Thanjavur, Tamil Nadu",
        "period": "Chola Dynasty (1010 CE)",
        "location_name": "Thanjavur Great Living Chola Temple",
        "latitude": 10.7828,
        "longitude": 79.1318,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Granite Vimana tower of Brihadisvara Temple in Thanjavur",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q667794) & UNESCO World Heritage",
        "source_url": "https://www.wikidata.org/wiki/Q667794",
        "license": "CC BY-SA 4.0 / Public Domain",
        "tags": "architecture,temple,chola,thanjavur,unesco",
    },
    {
        "slug": "mamallapuram-monuments",
        "title_ta": "மாமல்லபுரம் குடைவரைக் கோவில்கள்",
        "title_en": "Group of Monuments at Mamallapuram",
        "category": "Architecture",
        "summary_ta": "7 மற்றும் 8-ஆம் நூற்றாண்டுகளில் பல்லவ மன்னர்களால் உருவாக்கப்பட்ட பாறைக் குடைவரை சிற்பங்களின் சாம்ராஜ்யம்.",
        "summary_en": "7th-8th century UNESCO monument complex built by Pallava kings, famous for Pancha Rathas and Arjuna's Penance.",
        "content_ta": "மாமல்லபுரம் (மகாபலிபுரம்) பல்லவ வம்சத்தின் மாபெரும் துறைமுக நகரமாகும். முதலாம் நரசிம்மவர்மன் காலத்தில் பாறைகளைக் குடைந்து ரதங்கள், குகைக் கோவில்கள் மற்றும் சிற்பங்கள் செதுக்கப்பட்டன. 'அர்ஜுனன் தபஸ்' என்ற பிரம்மாண்ட பாறைச் சிற்பமும், வங்கக் கடலின் ஓரத்தில் அமைந்துள்ள கடற்கரைக் கோவிலும் (Shore Temple) உலகளவில் புகழ்பெற்றவை.",
        "content_en": "Mamallapuram was the vibrant port city of the Pallava Empire during the 7th and 8th centuries. The site features monolithic Pancha Rathas (chariots carved from single boulders), the mesmerizing open-air bas-relief sculpture 'Arjuna's Penance', and the seafront Shore Temple standing resilient against coastal tides for over 13 centuries.",
        "region": "Chengalpattu, Tamil Nadu",
        "period": "Pallava Dynasty (7th-8th Century CE)",
        "location_name": "Mamallapuram Coastal Heritage Site, Chengalpattu",
        "latitude": 12.6169,
        "longitude": 80.1927,
        "image_url": "https://images.unsplash.com/photo-1600100397608-f010e423b963?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Shore Temple at Mamallapuram carved overlooking the Bay of Bengal",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1526435) & UNESCO World Heritage",
        "source_url": "https://www.wikidata.org/wiki/Q1526435",
        "license": "CC BY-SA 4.0",
        "tags": "architecture,pallava,mamallapuram,sculpture,unesco",
    },

    # ---------------------------------------------------------------- Language & Traditions
    {
        "slug": "sangam-literature-legacy",
        "title_ta": "சங்க இலக்கியப் பாரம்பரியம்",
        "title_en": "Sangam Literature Legacy",
        "category": "Language & Traditions",
        "summary_ta": "பண்டைய மதுரையில் சங்கம் அமைத்து புலவர்களால் இயற்றப்பட்ட தமிழ் செவ்வியல் செய்யுள் தொகுப்புகள்.",
        "summary_en": "Ancient corpus of Tamil poetic works (Ettuthogai & Pattupattu) exploring human love (Akam) and ethics/war (Puram).",
        "content_ta": "சங்க இலக்கியம் என்பது கி.மு. 300 முதல் கி.பி. 300 வரையிலான காலத்தில் புலவர்களால் இயற்றப்பட்ட 2381 கவிதைகளின் தொகுப்பாகும். இது எட்டுத்தொகை மற்றும் பத்துப்பாட்டு என பிரிக்கப்பட்டுள்ளது. சங்க கவிதைகள் மனித உணர்வுகளை 'அகம்' (காதல், குடும்ப வாழ்வு) என்றும் 'புறம்' (வீரம், அறம், கொடை) என்றும் இருபெரும் பிரிவுகளாகப் பகுத்து உலகியல் தத்துவங்களை நயம்படக் கூறுகின்றன.",
        "content_en": "Sangam literature represents the dawn of classical Tamil civilization, spanning 2,381 surviving poems attributed to 473 poets (including 30 women poets). Divided into Ettuthogai (Eight Anthologies) and Pattupattu (Ten Idylls), it classifies human experience into Akam (internal, personal love and emotions) and Puram (external, honor, war, and philanthropy).",
        "region": "Ancient Tamilakam",
        "period": "300 BCE – 300 CE",
        "location_name": "Madurai Ancient Sangam Literary Site",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Palm-leaf manuscript heritage of ancient Tamil classical literature",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1276701) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1276701",
        "license": "CC BY-SA 4.0",
        "tags": "language,literature,sangam,poetry,traditions",
    },
    {
        "slug": "kolam-art",
        "title_ta": "கோலக் கலை (அரிசி மாவு கோலம்)",
        "title_en": "Kolam Threshold Art",
        "category": "Language & Traditions",
        "summary_ta": "தமிழர் இல்லங்களின் வாசலில் அரிசி மாவு கொண்டு தினமும் வரையப்படும் கணிதவியல் மற்றும் அழகியல் கோலங்கள்.",
        "summary_en": "Geometric floor pattern artwork drawn daily with dry rice flour at house thresholds to welcome harmony and feed small creatures.",
        "content_ta": "கோலம் என்பது தமிழ் சமூகத்தின் அன்றாட அழகியல் மற்றும் அறிவியல் பாரம்பரியமாகும். அதிகாலை வேளையில் வீட்டின் முற்றத்தைத் தெளித்து, புள்ளி வைத்து அரிசி மாவு கொண்டு கோலமிடுவார்கள். இது வீட்டிற்கு மங்கலத்தைக் கொண்டுவருவதோடு மட்டுமல்லாமல், எறும்புகள் மற்றும் பறவைகளுக்கு உணவளிக்கும் 'ஜீவகாருண்ய' தத்துவத்தையும் உள்ளடக்கியது. கோலப் புள்ளிகளின் கணித அமைப்பு உலகளவில் ஆராயப்படுகிறது.",
        "content_en": "Kolam is an everyday ritual of artistic discipline and ecological harmony practiced at sunrise across Tamil households. Drawn with unrefined rice flour on freshly swept thresholds, it serves as a silent invitation to prosperity while providing nourishment to ants, birds, and tiny insects. Computer scientists and mathematicians worldwide study the recursive symmetry and knot theory of Tamil Kolam motifs.",
        "region": "Tamil Nadu & South India",
        "period": "Ancient Household Practice",
        "location_name": "Kanchipuram & Mylapore Household Art Heritage",
        "latitude": 13.0336,
        "longitude": 80.2694,
        "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Intricate rice-powder Kolam pattern drawn at morning sunrise",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1778949) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1778949",
        "license": "CC BY-SA 4.0",
        "tags": "traditions,kolam,art,mathematics,harmony",
    },

    # ---------------------------------------------------------------- People
    {
        "slug": "thiruvalluvar",
        "title_ta": "திருவள்ளுவர்",
        "title_en": "Thiruvalluvar",
        "category": "People",
        "summary_ta": "உலகப் பொதுமறையான திருக்குறளை இயற்றிய உலகப் புகழ்பெற்ற தமிழ் சான்றோர் மற்றும் தத்துவஞானி.",
        "summary_en": "Venerated ancient Tamil poet-philosopher who authored the Thirukkural, comprising 1,330 couplets on ethics, wealth, and love.",
        "content_ta": "திருவள்ளுவர் தமிழ் மொழியின் ஒப்பற்ற மெய்ஞானியும் புலவருமாவார். இவர் இயற்றிய 'திருக்குறள்' 133 அதிகாரங்களில் 1,330 குறட்பாக்களைக் கொண்டது. மதம், இனம், மொழி கடந்து அறம் (Virtue), பொருள் (Wealth), இன்பம் (Love) ஆகிய மனித வாழ்வின் மூன்று முதன்மை விழுமியங்களை உலகளாவிய பார்வையுடன் விளக்குவதால் இது 'உலகப் பொதுமறை' என்று போற்றப்படுகிறது.",
        "content_en": "Thiruvalluvar is the celebrated secular philosopher of Tamil civilization. His masterwork, the Thirukkural, consists of 1,330 succinct two-line couplets organized into 133 chapters. Translated into over 40 global languages, the Thirukkural presents timeless ethical guidelines on statecraft, friendship, truth, humility, and domestic affection without favoring any single religious dogma.",
        "region": "Mylapore / Ancient Tamilakam",
        "period": "c. 5th Century BCE – 1st Century CE",
        "location_name": "Mylapore Valluvar Shrine, Chennai",
        "latitude": 13.0336,
        "longitude": 80.2694,
        "image_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Statue representation of Sage Thiruvalluvar holding palm manuscript",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q312480) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q312480",
        "license": "CC BY-SA 4.0",
        "tags": "people,thiruvalluvar,kural,poet,philosopher",
    },
    {
        "slug": "avvaiyar",
        "title_ta": "ஔவையார்",
        "title_en": "Avvaiyar",
        "category": "People",
        "summary_ta": "ஆத்திசூடி, கொன்றை வேந்தன் ஆகிய நீதி நூல்களை இயற்றிய தமிழ் பெண் புலவர் பெருமதிப்பிற்குரியவர்.",
        "summary_en": "Cherished lineage of ancient Tamil female poet-saints celebrated for wisdom, child ethics, and royal diplomacy.",
        "content_ta": "ஔவையார் என்பது தமிழ் வரலாற்றில் வாழ்ந்த பெண் ஞானிகளின் பொதுப் பெயராகும். சங்க காலத்தில் வாழ்ந்த ஔவையார் அதியமான் மன்னனின் நெருங்கிய நண்பராகவும் தூதராகவும் திகழ்ந்தார். பிற்காலத்தில் வாழ்ந்த ஔவையார் குழந்தைகளுக்கு அறநெறிகளை கற்பிக்கும் 'ஆத்திசூடி', 'கொன்றை வேந்தன்', 'நல்வழி' ஆகிய எளிய நீதி நூல்களை இயற்றினார். 'அறம் செய விரும்பு' என்பது இவரது புகழ்பெற்ற வரிகளாகும்.",
        "content_en": "Avvaiyar ('Venerable Woman') refers to a revered lineage of female poets in Tamil literary history. The Sangam-era Avvaiyar was a fearless diplomat and advisor to King Athiyaman. A later medieval Avvaiyar composed foundational ethical texts for children like Aathichudi and Kondrai Vendhan, instilling moral clarity through memorable single-line aphorisms such as 'Aram Seya Virumbu' (Desire to perform righteous deeds).",
        "region": "Tamilakam",
        "period": "Sangam & Medieval Eras",
        "location_name": "Tiruttani & Athiyaman Kingdom Trail, Dharmapuri",
        "latitude": 12.1211,
        "longitude": 78.1582,
        "image_url": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Representation of Avvaiyar imparting wisdom through Tamil literature",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534575) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534575",
        "license": "CC BY-SA 4.0",
        "tags": "people,avvaiyar,poet,ethics,aathichudi",
    },

    # ---------------------------------------------------------------- History
    {
        "slug": "chola-dynasty",
        "title_ta": "சோழப் பேரரசு",
        "title_en": "The Chola Empire",
        "category": "History",
        "summary_ta": "தென்கிழக்கு ஆசியா வரை கடற்படை செலுத்தி ஆட்சி செய்த உலக வரலாற்றின் நீண்டகாலக் கப்பற்படைப் பேரரசு.",
        "summary_en": "One of longest-ruling maritime empires in history (300 BCE – 1279 CE), famous for naval power and temple arts.",
        "content_ta": "சோழ வம்சம் தென்னிந்திய வரலாற்றில் மிகவும் சக்திவாய்ந்த பேரரசாகும். முதலாம் ராஜராஜ சோழன் மற்றும் அவரது மகன் முதலாம் ராஜேந்திர சோழன் காலத்தில் சோழப் பேரரசு இலங்கை, மாலத்தீவு, மலேசியா, இந்தோனேசியா மற்றும் தாய்லாந்து வரை கடற்படை வாயிலாகத் தனது ஆதிக்கத்தைப் பரப்பியது. திறமையான உள்ளாட்சி கிராம நிர்வாக முறை (குடவோலை முறை) மற்றும் சோழர் வெண்கலச் சிற்பங்கள் உலகப் புகழ்பெற்றவை.",
        "content_en": "The Chola Dynasty is celebrated as one of the greatest maritime empires of Asia, spanning from antiquity through its imperial height (9th-13th century CE). Under monarchs Raja Raja Chola I and Rajendra Chola I, the Chola navy crossed the Bay of Bengal to establish trade dominance over Sri Lanka and the Srivijaya Empire in Southeast Asia while pioneering democratic village governance (Kudavolai electoral system).",
        "region": "Kaveri Delta to Southeast Asia",
        "period": "300 BCE – 1279 CE",
        "location_name": "Gangaikondacholapuram Imperial Seat, Ariyalur",
        "latitude": 11.2064,
        "longitude": 79.4485,
        "image_url": "https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Bronze Nataraja sculpture crafted during the Chola golden age",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q151148) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q151148",
        "license": "CC BY-SA 4.0",
        "tags": "history,chola,empire,maritime,rajaraja",
    },
    {
        "slug": "sangam-period",
        "title_ta": "சங்க காலம்",
        "title_en": "The Sangam Period",
        "category": "History",
        "summary_ta": "சேர, சோழ, பாண்டிய மூவேந்தர்கள் தமிழ் நிலத்தை ஆண்டு இலக்கியத்தையும் வணிகத்தையும் வளர்த்த பொற்காலம்.",
        "summary_en": "The classical era of ancient South India governed by the Chera, Chola, and Pandya dynasties.",
        "content_ta": "சங்க காலம் என்பது பண்டைய தமிழ்நாட்டின் செவ்விலக்கிய நாகரிகக் காலமாகும். மூவேந்தர்களான சேரர், சோழர், பாண்டியர்கள் இக்காலத்தில் ஆட்சி செய்தனர். மதுரை, பூம்புகார், முசிறி போன்ற நகரங்கள் ரோமானியப் பேரரசு மற்றும் கிரேக்கம் வரை உலகளாவிய கடல் வணிகத்தில் சிறந்து விளங்கின. துறைமுகங்களில் முத்து, நறுமணப் பொருட்கள், நெசவு உடைகள் ஏற்றுமதி செய்யப்பட்டன.",
        "content_en": "The Sangam Era marks the golden age of ancient South Indian history under the patronage of the Three Crowned Kings (Chera, Chola, and Pandya). Ancient port cities like Poompuhar, Muziris, and Arikamedu engaged in extensive maritime trade with the Roman Empire and Ancient Greece, exporting spices, pearls, fine textiles, and beryl.",
        "region": "Tamilakam",
        "period": "c. 3rd Century BCE – 3rd Century CE",
        "location_name": "Korkai Ancient Pandyan Port, Thoothukudi",
        "latitude": 8.6333,
        "longitude": 78.0500,
        "image_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Historical artifacts and coin trade relics from the Sangam Era",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q3534002) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q3534002",
        "license": "CC BY-SA 4.0",
        "tags": "history,sangam,chera,chola,pandya",
    },

    # ---------------------------------------------------------------- Places
    {
        "slug": "madurai-meenakshi",
        "title_ta": "மதுரை மீனாட்சி அம்மன் கோவில்",
        "title_en": "Madurai & Meenakshi Temple",
        "category": "Places",
        "summary_ta": "தூங்கா நகரம் எனப்படும் பண்டைய மதுரையின் மையத்தில் அமைந்துள்ள 14 பிரம்மாண்ட கோபுரங்கள் கொண்ட கலைக் கோவில்.",
        "summary_en": "Ancient city of Madurai centered around the iconic 14-gopuram sanctuary dedicated to Goddess Meenakshi.",
        "content_ta": "மதுரை உலகிலேயே பழமையான தொடர்ந்து மக்கள் வாழும் நகரங்களில் ஒன்றாகும். இது 'தூங்கா நகரம்' என்றும் 'சங்க நகரம்' என்றும் அழைக்கப்படுகிறது. மதுரையின் மையத்தில் அமைந்துள்ள மீனாட்சி சொக்கநாதர் கோவில் 14 வண்ணமயமான உயரமான கோபுரங்களையும், 1000 கால் மண்டபத்தையும் கொண்டது. இக்கோவிலின் சிற்பக்கலையும் ஆயிரங்கால் மண்டப இசைத் தூண்களும் உலகப் புகழ்பெற்றவை.",
        "content_en": "Madurai is one of the oldest continuously inhabited cities in the world, often revered as the 'City of Nectar' and 'Sleepless City'. At its heart stands the majestic Meenakshi Amman Temple complex featuring 14 soaring gopurams (gateway towers) encrusted with thousands of colorful stone figures, a sacred Golden Lotus pond, and the famous Hall of 1000 Pillars.",
        "region": "Madurai, Tamil Nadu",
        "period": "Pandya Era to Nayak Architecture",
        "location_name": "Madurai Meenakshi Temple Complex",
        "latitude": 9.9195,
        "longitude": 78.1193,
        "image_url": "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Towering polychrome Gopuram of Madurai Meenakshi Temple",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q1427510) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q1427510",
        "license": "CC BY-SA 4.0",
        "tags": "places,madurai,meenakshi,temple,gopuram",
    },
    {
        "slug": "thanjavur",
        "title_ta": "தஞ்சாவூர் நகரம்",
        "title_en": "Thanjavur (Tanjore)",
        "category": "Places",
        "summary_ta": "சோழர்களின் தலைநகரமும், தமிழ் இசை, தலையாட்டி பொம்மை மற்றும் ஓவியங்களின் கலைத் தலைநகரமும் ஆகும்.",
        "summary_en": "Cultural capital of the Cholas, famed for Tanjore paintings, bobblehead dolls, and Veena crafting.",
        "content_ta": "தஞ்சாவூர் தமிழ்நாட்டின் கலாச்சார மற்றும் நெற்களஞ்சிய தலைநகரமாகும். காவிரி ஆற்றின் வளத்தால் 'டெல்டா மாவட்டம்' என்று அழைக்கப்படுகிறது. சோழர்களின் தலைநகரமாக விளங்கிய இந்நகரம் தஞ்சாவூர் ஓவியங்கள், தஞ்சாவூர் தலையாட்டி பொம்மைகள், வீணை தயாரிப்பு மற்றும் செவ்வியல் இசைக்குப் பெயர் பெற்றது.",
        "content_en": "Thanjavur (Tanjore) is the cultural heartland of Tamil Nadu situated in the fertile Kaveri Delta. As the historic capital of the imperial Cholas, it gave birth to Tanjore gold-leaf paintings, uniquely balanced bobblehead dolls (Thanjavur Thalaiyatti Bommai), Saraswati Veena instrument crafting, and South Indian classical music traditions.",
        "region": "Kaveri Delta, Tamil Nadu",
        "period": "Chola Heritage City",
        "location_name": "Thanjavur Royal Palace & Art District",
        "latitude": 10.7870,
        "longitude": 79.1378,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "image_caption": "Heritage landscape of Thanjavur cultural heartland",
        "source_type": "wikidata",
        "source_name": "Wikidata (Q207865) & Ezhuthaani Editorial",
        "source_url": "https://www.wikidata.org/wiki/Q207865",
        "license": "CC BY-SA 4.0",
        "tags": "places,thanjavur,art,culture,chola",
    },
]
